<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_toggleShowInactive</name>
   <tag></tag>
   <elementGuidId>74fc076f-b8cf-4716-96ae-0a65b27c837d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggleShowInactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'toggleShowInactive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toggleShowInactive</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eafd04d2-90b4-4939-9770-5c6b5680669c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b1baf127-8804-4172-ad30-b89bedbadeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>048f4e21-a3b9-46d2-b5e9-859d78a7fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggleShowInactive</value>
      <webElementGuid>0b31420b-37ac-4024-bf0e-9dc30418f834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2a7c7c9fef31b503e495935d4113535d</value>
      <webElementGuid>2ed3c28a-e5c1-4fe0-8f90-9cc9855d4172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'toggleShowInactive']</value>
      <webElementGuid>6a075ac5-24d0-4235-ae9f-83ac159dfeb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'toggleShowInactive']</value>
      <webElementGuid>18f7ea39-a9af-42b3-a730-f71de0742f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'toggleShowInactive']</value>
      <webElementGuid>f8ed1188-c21e-4ba9-af0c-62fe244e8002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
