<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email Address Input</name>
   <tag></tag>
   <elementGuidId>aaae6dc7-dbfc-44d4-90aa-d265073169aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;contact@yourpractice.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fe4c96f-f994-42c3-bde9-d0a9c99bb904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>aecd38e0-596e-4218-8d19-d80b102f2682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>196aa453-1134-48d2-b8c8-1e10cfd10faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>098a04ac-a6d8-4e6c-95f1-ddae0dbdac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>contact@yourpractice.com</value>
      <webElementGuid>1b0f768a-7550-4689-a6c9-351fe301c22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>d27a7489-e943-482d-8cc0-ef1a7fb3152e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>a68bca6b-02fb-4ec9-9291-66bb18cbb2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailAddress&quot;)</value>
      <webElementGuid>4318b816-fc4d-4ba7-b0a5-8958dfc46712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailAddress']</value>
      <webElementGuid>4735cbfc-7c20-4fd9-8751-da6c14e68add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>cbade493-ba05-47b9-9abd-b937d6a659fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailAddress' and @name = 'EmailAddress' and @type = 'text' and @placeholder = 'contact@yourpractice.com']</value>
      <webElementGuid>9e668f62-09da-4eba-91d3-be4373875b09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
