<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Organization Name</name>
   <tag></tag>
   <elementGuidId>e7a0a399-4ee8-4c36-8f5b-cdea1dfc7852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OrgName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OrgName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your organization name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>477eeb9c-d36c-4da9-9e46-70888219cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OrgName</value>
      <webElementGuid>f9b39355-2c69-45fa-9772-a2714e279508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OrgName</value>
      <webElementGuid>cb8b45cf-2717-4ca8-b091-d7124514299d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd2e2625-16cf-403e-b441-dd65ca862788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your organization name</value>
      <webElementGuid>e7521dc2-7d3b-4d84-b8fb-8e2645f28359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3b0df6f9-ba22-45fa-afa1-75954ae89bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrgName&quot;)</value>
      <webElementGuid>899b3bf6-19e2-4784-b6e6-051c78c09e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OrgName']</value>
      <webElementGuid>ef20387b-9315-4903-b4ba-8154a62f59c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2c62c461-3572-4fda-ae47-b846fc9e5377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OrgName' and @name = 'OrgName' and @type = 'text' and @placeholder = 'Enter your organization name']</value>
      <webElementGuid>73e3d555-cdf7-4e6c-89df-6ea64686472c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
