<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tax ID_TaxId input</name>
   <tag></tag>
   <elementGuidId>0d4c94be-873a-44d7-b3dd-c2512b66b1d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaxId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TaxId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;XX-XXXXXXX&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41127ab3-9b1f-49c4-9b28-4c4e3ad3f123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaxId</value>
      <webElementGuid>12d695bb-4dc5-4851-a2b2-42659da3b0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TaxId</value>
      <webElementGuid>0c86529f-4615-45f2-8bb7-6da7ea75c875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4335f625-79f7-4628-bc98-a49bc3d6024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>13714563-4450-4159-9828-379ae4a345ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{9}</value>
      <webElementGuid>54c419e1-5cce-4283-b887-25bdcb246f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XX-XXXXXXX</value>
      <webElementGuid>ed810648-4098-4d8c-a3e1-f45dd3ff445b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tax ID must be exactly 9 digits.</value>
      <webElementGuid>640356e9-b634-4843-a32f-8b5f1d947e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaxId&quot;)</value>
      <webElementGuid>28b612b9-e74f-46dd-83e3-32ac0e5ee0e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TaxId']</value>
      <webElementGuid>d44fee42-1223-4546-ad16-376bb86c1706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a816acc7-9fea-4d6f-a501-cfdb8671d296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TaxId' and @name = 'TaxId' and @type = 'tel' and @placeholder = 'XX-XXXXXXX' and @title = 'Tax ID must be exactly 9 digits.']</value>
      <webElementGuid>c97677a0-7618-435e-b929-715e52b9f935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
