<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website or Preferred EVAA Subdomain</name>
   <tag></tag>
   <elementGuidId>fb43cf24-b150-49e3-b9d9-c19f7a9a82ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Subdomain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Subdomain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g.yourpractice.evaa.ai or https://www.yourwebsite.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5968976-a455-4f68-9903-b9ada21100e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subdomain</value>
      <webElementGuid>2a39edac-a33a-41c3-b93a-a676a64e50ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>1c9d63fe-f1e0-4510-bb40-9d5ab1a5a8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99ff33d1-dd1e-4afd-8346-1e77383156d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g.yourpractice.evaa.ai or https://www.yourwebsite.com</value>
      <webElementGuid>3d7bb9f8-f748-4a85-9d43-2b76f4a03e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>eaf2bfb3-fd16-4bae-8b5a-7f2cc4ff900c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subdomain&quot;)</value>
      <webElementGuid>06ea660c-98a6-4d10-9467-ba7a494538ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Subdomain']</value>
      <webElementGuid>c37cc512-ed69-4152-90af-da4ea50cf855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>4093995f-d14e-4f4a-908f-03e7fcb69cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Subdomain' and @name = 'Website' and @type = 'text' and @placeholder = 'e.g.yourpractice.evaa.ai or https://www.yourwebsite.com']</value>
      <webElementGuid>b8faf196-005e-4385-baac-24e24b8e5041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
