<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Electronic Signature_signature-input_5</name>
   <tag></tag>
   <elementGuidId>2f90a335-45c7-418d-9d58-d505b4e8062a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='testq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.signature-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f18a5c27-2f6e-4242-938a-74916a3cbaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signature-input</value>
      <webElementGuid>04f43e71-8fbd-4939-b308-8fcaa96226df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your name</value>
      <webElementGuid>0da0b5a8-f236-45fd-9a5e-d74e4c360a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3289f9c5-3835-499b-bdfe-5f6922a69fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testq</value>
      <webElementGuid>52ccc971-49fb-4f09-a61e-7e2c0c0e7fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;route-fade-in&quot;]/div[@class=&quot;layout layout-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;service-agreement-page&quot;]/div[@class=&quot;agreement-container&quot;]/div[@class=&quot;agreement-content&quot;]/div[@class=&quot;signature-section&quot;]/input[@class=&quot;signature-input&quot;]</value>
      <webElementGuid>142a62de-bf01-49ed-ae14-244f269f47f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/demo/Page_Unified Admin/iframe</value>
      <webElementGuid>a4efa62c-bde2-4699-bcf3-8a50aef9547a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='testq']</value>
      <webElementGuid>0d1dca79-7036-4990-81f7-66186a970bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>5a3cb5c5-cc85-4038-8093-b887f7501884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bcda8bc3-ef44-423b-a4f5-13194366e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your name' and @type = 'text']</value>
      <webElementGuid>5f6229f8-1db1-43d5-bc1a-96449a41a12f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
