<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Inactive_1</name>
   <tag></tag>
   <elementGuidId>cb46d554-f0c3-4925-8a84-203dad966598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showInactiveSwitch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'showInactiveSwitch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show Inactive&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7ddc8e6-2308-4cbc-8b59-83ce10d3f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-toggle-input</value>
      <webElementGuid>3f02d367-90f8-4b9a-8cec-7d53dcfe19be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d701e91f-907e-468e-a847-26824fae9f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showInactiveSwitch</value>
      <webElementGuid>d83c8ddf-482d-4671-ab7d-9f4d2656bf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-caeb6fed3c69acb5d88d204b4339f657</value>
      <webElementGuid>586aa3c7-e41c-48f4-88ad-2019ca0befbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'showInactiveSwitch']</value>
      <webElementGuid>cf5f6dba-6b05-41a5-9782-0f04a8e83e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'showInactiveSwitch']</value>
      <webElementGuid>c0425fa8-7ec1-442f-a356-aa66c9e7856d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'showInactiveSwitch']</value>
      <webElementGuid>03af0634-be9e-4ca1-9d51-7eccc0473bba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
