<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Use new card___privateStripeFrame5564</name>
   <tag></tag>
   <elementGuidId>8bd0dfb1-4bcc-4c72-918d-d2841c671d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame5564&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame5564']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;__privateStripeFrame5564&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>304bf241-62f4-4d2c-b8f5-404740d2847a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame5564</value>
      <webElementGuid>974b5a0c-4163-4d37-a178-289cc901e360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>190c10b7-d135-43ea-8294-6a352e60f01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f06f0586-4e95-4335-84dd-602df7394861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8a330e6f-34fa-49f3-b63f-56df7ff1c325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>222dcb35-2fa3-4326-bb76-71629c628d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *; publickey-credentials-get *</value>
      <webElementGuid>4d871bb8-2cd9-4937-be1f-f5e57b9a0812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-accessory-target-dc43a497995e60f54b963b22dcbd0824.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%22796cc286-ff57-48f8-959e-708e0f33d234%22%2C%22assignments%22%3A%7B%22elements_accessory_frame_rendering_v5%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-8e76e2fe-ba36-42aa-9d89-bfb8fd98e859&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;accessoryCssUrl=https%3A%2F%2Fjs.stripe.com%2Fv3%2Ffingerprinted%2Fcss%2Felements-inner-payment-5197bd0f78884ca270582acfb8fca9aa.css&amp;referrer=https%3A%2F%2Fpay-dev1.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController5561</value>
      <webElementGuid>4de3e430-8e75-4e6d-87b7-16d441fa36a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>cfeeef12-c9d0-416f-a969-229859b7dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>2a6e2af8-d0dd-4cac-98f3-36805175623f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Payment Page/Page_Unified Admin/iframe</value>
      <webElementGuid>aa09f0ef-98a4-4735-a8ff-386ea66ddc51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame5564']</value>
      <webElementGuid>37c54967-1b80-43b4-befa-5b8559bae619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-element']/div/iframe</value>
      <webElementGuid>1e7bdbd0-99b1-4baa-9ddf-0b2a5a0af08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>625012ed-54e7-4672-a033-41faf3584153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame5564' and @src = 'https://js.stripe.com/v3/elements-inner-accessory-target-dc43a497995e60f54b963b22dcbd0824.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%22796cc286-ff57-48f8-959e-708e0f33d234%22%2C%22assignments%22%3A%7B%22elements_accessory_frame_rendering_v5%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-8e76e2fe-ba36-42aa-9d89-bfb8fd98e859&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;accessoryCssUrl=https%3A%2F%2Fjs.stripe.com%2Fv3%2Ffingerprinted%2Fcss%2Felements-inner-payment-5197bd0f78884ca270582acfb8fca9aa.css&amp;referrer=https%3A%2F%2Fpay-dev1.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController5561' and @title = 'Secure payment input frame']</value>
      <webElementGuid>de2c7944-a045-40e7-937e-9172af0a9766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
