<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Setup</name>
   <tag></tag>
   <elementGuidId>d6024a2b-dcbd-4dbc-9542-1fbd454ca871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-black ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.font-black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Setup&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcd9b28d-16d1-463e-b899-1d9f7266e567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e195bc5-b90d-4fca-8275-bf706d0844d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex items-center justify-between px-3 py-2 text-[14px] font-black text-[#303030] hover:bg-[#ffebf6] rounded-[5px] transition-colors border-0 bg-transparent</value>
      <webElementGuid>75d1c8bf-07cc-4cc9-a98f-bc37c18b0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e1ed0a8-4d2f-4aaf-bb3c-c71ca1a54c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setup</value>
      <webElementGuid>554a5eb6-faa2-4e8a-ab02-8a6a256f4713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-72f1ccd557ec3d56a946c0b679e953b4</value>
      <webElementGuid>f4f6d25a-f1b9-433c-a54d-7a537e1de641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-black ')]</value>
      <webElementGuid>647bdafd-b0e1-4513-bbe2-e5a09bb597f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-black ')]</value>
      <webElementGuid>36b8ae7a-0cdf-47af-8a0b-e7b991ae08b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Setup' or . = 'Setup')]</value>
      <webElementGuid>5ed75ab7-2268-4209-b4f6-4f8692b711f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
