<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_None</name>
   <tag></tag>
   <elementGuidId>af3a0721-4d53-4b5a-8521-facec08d2674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.whitespace-nowrap.text-sm.\*\:data-\[slot\=select-value\]\:flex.max-w-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:has-text=&quot;None&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26d364c1-2607-4d41-b17a-5dc83a185a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf6089fd-ce8c-408c-b006-b5731d909609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>062bfa45-7d76-4685-8f57-680e4f41349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r2e:</value>
      <webElementGuid>e33f8c8a-37bc-423e-824f-72abc0725158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30ec3c83-8f11-4678-8d5d-abbef827f34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b307f631-46a1-43b9-9c76-15baf992bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>c28ca893-0973-4c1f-879f-0a1921bac5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>4be0f818-8b25-46c6-9f81-d3e82222d8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>select-trigger</value>
      <webElementGuid>a0d261a9-cc2c-4ed6-b188-2d7fa83546dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>26f7572f-98ed-4b35-b525-9a9c7408f64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-[#d0cec3] data-[placeholder]:text-[#6b7280] [&amp;_svg:not([class*='text-'])]:text-[#4b5563] flex items-center justify-between gap-2 overflow-hidden border px-3 py-2 text-sm text-[#1a1a1a] whitespace-nowrap transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-[#b80e74]/30 disabled:cursor-not-allowed disabled:opacity-50 disabled:text-[#9ca3af] data-[size=default]:h-9 data-[size=sm]:h-8 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center *:data-[slot=select-value]:gap-2 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 w-full max-w-md !rounded-[13px] bg-white</value>
      <webElementGuid>1cce51d8-16b3-4033-8351-40b9d3a5c6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>bd090d7e-e99c-4458-8590-db7c5538e75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ce5b8501c5c2127fa8be5b2f76ede005</value>
      <webElementGuid>43eb3928-310b-4485-a6a9-ccbc0daae466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      <webElementGuid>b5c088dd-45e3-4d78-a997-157a720c88bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      <webElementGuid>ca13d580-a38b-446b-bebf-18302d149fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'None' or . = 'None')]</value>
      <webElementGuid>3a100406-8bcc-4454-b82a-42beec81aee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
