<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextGen EHR Radio Button</name>
   <tag></tag>
   <elementGuidId>e57f8502-50b7-434c-bdc9-6784a34faca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ehr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ehr-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NextGen&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4bcca28-109e-45d1-9ee9-87a59ee3426f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-radio</value>
      <webElementGuid>7b12f576-d2ad-4ee3-9d9a-8e522a38606a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>81fb127b-f228-4006-bd3e-6a06670eea72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ehrSystem</value>
      <webElementGuid>f5d2e353-9bfe-4764-95c9-c455c093ffe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ehr-2</value>
      <webElementGuid>84e1d7cb-496e-42c8-8435-42e50d36e9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NextGen</value>
      <webElementGuid>2a7f3801-76f4-4664-9707-4c4873efc0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ehr-2&quot;)</value>
      <webElementGuid>f1f62247-15a7-4feb-a6a4-c6a3439ee21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ehr-2']</value>
      <webElementGuid>108013ff-96e6-4911-9f71-b8a86a499d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>da936cef-294e-47c5-94d2-9e1e71dfb0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c325f340-d261-4239-9476-87380df0eac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ehrSystem' and @id = 'ehr-2']</value>
      <webElementGuid>9c53c600-14d6-4108-99c6-6eec5e8ab7a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
