<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website or Preferred EVAA Subdomain_S_ca93d8</name>
   <tag></tag>
   <elementGuidId>1bee2d37-8eff-47e2-89f1-d0b9e9eae2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Subdomain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Subdomain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g.yourpractice.evaa.ai or https://www.yourwebsite.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2371163-4a06-4eb8-84a9-90f25593895f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subdomain</value>
      <webElementGuid>52896b58-f6ea-45db-8eae-5d50fe00abfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>55186d29-6a65-4b52-8f9d-1bc7aa3666bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1404e1d1-6974-4ff5-b96e-cb3686d07039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g.yourpractice.evaa.ai or https://www.yourwebsite.com</value>
      <webElementGuid>a3e79f39-5430-4bed-a661-9fcd75c35ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c8a910a4-1175-4317-bfa9-fec6ae7bef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subdomain&quot;)</value>
      <webElementGuid>85d0cc61-a212-4619-9673-bcd8c2336a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Subdomain']</value>
      <webElementGuid>7277565c-2613-471c-995f-e3117f0b0cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>cf14d4fc-3c67-46a4-86be-cf665a7d310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Subdomain' and @name = 'Website' and @type = 'text' and @placeholder = 'e.g.yourpractice.evaa.ai or https://www.yourwebsite.com']</value>
      <webElementGuid>73e37222-9bfc-4d67-af02-64fbaaa0b15f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
