<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reschedule</name>
   <tag></tag>
   <elementGuidId>84b72435-4897-4b18-9a44-118fab68e909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.wizard-footer-row:nth-child(3) .wizard-btn.wizard-btn--next:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-footer-row ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn ') and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn--next ') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reschedule&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db5c9311-5344-4299-a5bc-a54f94f22957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d91b977-c3b4-4b4e-8225-ba34a044a52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-btn wizard-btn--next</value>
      <webElementGuid>fad8affa-de51-4bb3-86a5-30f69ad13d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reschedule</value>
      <webElementGuid>30bd78c1-539a-4795-bed0-04170aa3d001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3c05d6de22a32737d75f336053f61281</value>
      <webElementGuid>fd857cfe-d8f2-465c-b18f-8a3b4e5cf469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-footer-row ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn ') and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn--next ') and (position() = 1)]</value>
      <webElementGuid>a24c4459-3ae4-4036-9b05-ae0f0c5341fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/iframe_evaas-iframeId</value>
      <webElementGuid>4ae54e05-1783-43f1-8210-58166078ee4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-footer-row ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn ') and contains(concat(' ', normalize-space(@class), ' '), ' wizard-btn--next ') and (position() = 1)]</value>
      <webElementGuid>33293d28-6956-4c30-8638-314a707810be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Reschedule' or . = 'Reschedule')]</value>
      <webElementGuid>9577ba34-40c6-4cfd-9e93-eb3e42011951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
