<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Provider</name>
   <tag></tag>
   <elementGuidId>455ab630-32db-445b-8f29-6e7a9571b587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Provider*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c82b561c-cb4f-4e75-bb02-4718ed1cf15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provider</value>
      <webElementGuid>f080d405-2928-449d-b64d-f43547d08c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-select</value>
      <webElementGuid>1c9b73e0-e793-4b24-9658-21ba9dc4705b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select provider</value>
      <webElementGuid>13b2b13b-1297-45c5-8570-7f9cafacfdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b6a039050d66c6d0676e24ac3db667af</value>
      <webElementGuid>622fd988-8e5f-4733-9c78-e749c1af17cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'provider']</value>
      <webElementGuid>fc0ed722-bd30-4bdd-8236-7be678067cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/iframe_evaas-iframeId</value>
      <webElementGuid>b4a12fc5-3a22-4536-aef3-57e8f644c1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'provider']</value>
      <webElementGuid>f9d59f2f-a5c2-45d8-8ba2-ba90a36f7611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'provider' and (text() = 'Select provider' or . = 'Select provider')]</value>
      <webElementGuid>7be846e6-c004-4d66-a979-9b678aab197a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
