<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextGen EHR Radio Button (1)</name>
   <tag></tag>
   <elementGuidId>7019663c-2c11-487e-aebe-2efcc2544120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ehr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ehr-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NextGen&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d0f93eb-abd7-445c-9038-d1145642c25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-radio</value>
      <webElementGuid>9a4e8e25-f08c-4d3f-ae5b-bacfe11f434f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>99760257-145a-4114-89b9-35de3e2d66c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ehrSystem</value>
      <webElementGuid>c58240fa-c094-4946-a555-eb8762bd817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ehr-2</value>
      <webElementGuid>fec81d23-994c-45da-b19f-b2acf6db7e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NextGen</value>
      <webElementGuid>0e5abeed-0c85-40ba-b4be-86b4430c3760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ehr-2&quot;)</value>
      <webElementGuid>3f47d661-4332-41f3-91f1-9f550fee285e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ehr-2']</value>
      <webElementGuid>adfa687b-5707-49da-aa86-2e1e33f66222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>75f6a5c0-de70-4933-ac93-68cf47df3fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>43d433a8-198d-47e5-81c3-13f15b21e014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ehrSystem' and @id = 'ehr-2']</value>
      <webElementGuid>7e6945b5-1712-4c55-8206-14c59c2e6004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
