<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>0a15d2f5-c9b4-463b-adc0-88e9b5d2f260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/virtual-assistant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/virtual-assistant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dded987a-4637-480b-bff3-1dc3d0e53df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex items-center gap-2 px-3 py-2 text-[14px] font-semibold rounded-[5px] transition-colors no-underline text-[#4b4b4a] hover:bg-[#ffebf6]</value>
      <webElementGuid>968c1936-e724-4bef-bd4a-000b03aff4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/virtual-assistant</value>
      <webElementGuid>8f3e678f-5275-44c5-81d1-543aae9cc3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97863f42-5ffa-4c2a-8b37-4bf0805e2627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>61bc00d4-0bfa-430b-86f4-22655cf99af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7ce433c723ab993aaeecde7146cd9e72</value>
      <webElementGuid>98801a0b-b324-4307-aa42-7c0db7cc4587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant']</value>
      <webElementGuid>3f7df0bb-4b93-4827-b09b-5ac70be14014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant']</value>
      <webElementGuid>397fb9cf-4089-48a9-b43c-0dfebd911943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/virtual-assistant' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>438dcb86-7a19-4425-baba-a5d2c1b12c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
