<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Embedded_Share</name>
   <tag></tag>
   <elementGuidId>62acfb31-6150-4982-ab70-b12df7564ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/virtual-assistant/setup/embedded-share']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/virtual-assistant\/setup\/embedded-share&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Embedded/Share&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>216dc2a6-12c2-4297-bd84-526efdbae4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left px-3 py-2 text-[12px] rounded-[5px] transition-colors no-underline block font-normal text-[#70706c] hover:bg-[#ffebf6]</value>
      <webElementGuid>58669e0c-126d-487b-a069-6ce5c0667f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/virtual-assistant/setup/embedded-share</value>
      <webElementGuid>5b104f94-a2c7-4b1b-8a7e-5f7a2a212195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>147356eb-052c-4057-90c4-28bd36cf8b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Embedded/Share</value>
      <webElementGuid>bc1adc8d-e2db-4a56-8b14-77a4b42d4bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0a0824839b0e3421ca5c44deed644506</value>
      <webElementGuid>4ae4c777-463b-429a-bbf9-d3ad504e8037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/embedded-share']</value>
      <webElementGuid>957347b8-d193-40c2-92f1-3be31873f54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/embedded-share']</value>
      <webElementGuid>111a7aeb-1150-4aaf-9144-5c867f502a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/virtual-assistant/setup/embedded-share' and (text() = 'Embedded/Share' or . = 'Embedded/Share')]</value>
      <webElementGuid>e240f9f9-4e6b-4690-8c2f-b9286f1ac845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
