<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preferences</name>
   <tag></tag>
   <elementGuidId>ce99a4e1-8442-435b-8f4b-5eb8e140b4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/virtual-assistant/setup/preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/virtual-assistant\/setup\/preferences&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Preferences&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b44f38be-e6aa-4a48-8b8d-49e9c031438f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left px-3 py-2 text-[12px] rounded-[5px] transition-colors no-underline block font-normal text-[#70706c] hover:bg-[#ffebf6]</value>
      <webElementGuid>c05661a9-0ac1-4ecf-91e8-938ccd8ba13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/virtual-assistant/setup/preferences</value>
      <webElementGuid>559c9b2f-23e7-49b8-a574-b427e58b6ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dafbd532-666e-44fd-be72-7a585d911bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preferences</value>
      <webElementGuid>955e7d30-a79d-4496-b292-cebce4258c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c113d126d099fe7764208ecb1e8bd2b1</value>
      <webElementGuid>88ae7d40-1dbf-40e1-bb47-62d78ac4bcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/preferences']</value>
      <webElementGuid>c681e4d8-587c-49d1-b21e-45a091009977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/preferences']</value>
      <webElementGuid>d12071d2-a675-4545-a760-9d4345a59810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/virtual-assistant/setup/preferences' and (text() = 'Preferences' or . = 'Preferences')]</value>
      <webElementGuid>f06ecf0f-ebea-4e2b-9895-6dd263654036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
