<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Voicemail</name>
   <tag></tag>
   <elementGuidId>8e368b73-97dc-4d22-9146-a852280de73f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/virtual-assistant/setup/voicemail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/virtual-assistant\/setup\/voicemail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Voicemail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49ca53d4-a82e-49d8-917e-d9efe5d83bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left px-3 py-2 text-[12px] rounded-[5px] transition-colors no-underline block font-normal text-[#70706c] hover:bg-[#ffebf6]</value>
      <webElementGuid>90050309-0298-49b6-b722-b43c6067ce02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/virtual-assistant/setup/voicemail</value>
      <webElementGuid>21f3b716-97a0-4f78-9371-1686ae7a5811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e1d3924-a91d-4af0-b2aa-774cb55612c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voicemail</value>
      <webElementGuid>3953c1aa-c46b-498c-ac35-df99442ca61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-daeff6b3671842c21bb1aff0d40d24af</value>
      <webElementGuid>10ea5af4-4330-4597-8916-ebe70230cb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/voicemail']</value>
      <webElementGuid>9c1e5c65-9af4-4f0b-b943-6f5c117daf22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant/setup/voicemail']</value>
      <webElementGuid>1cebd9bf-f0d0-4b4e-b813-2ac394a65f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/virtual-assistant/setup/voicemail' and (text() = 'Voicemail' or . = 'Voicemail')]</value>
      <webElementGuid>8ee76ad0-53d9-438d-8b05-7bf25cea04fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
