<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select an Assistant</name>
   <tag></tag>
   <elementGuidId>1d6e7cf2-26a9-4d9f-a8e7-eefa1f647d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-light ') and contains(concat(' ', normalize-space(@class), ' '), ' dropdown-toggle ') and (@title = '')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn.btn-light.dropdown-toggle[title=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Select an Assistant&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7010330f-af83-492f-86d8-8e2f0d8e72db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light dropdown-toggle d-flex align-items-center gap-2</value>
      <webElementGuid>ebb422d8-4477-4918-b2f0-d87559216490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d91a4eb-8b21-40e0-a9f3-7ef30dab899e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>78a95f44-c310-4f2d-b3a7-d8b705708983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1d6bf91-a094-4128-abca-eba17e974427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an Assistant</value>
      <webElementGuid>09adbf52-f3dd-40c5-a526-e255d6d261c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2cba94e8c7c692b08eebffbca15fc1eb</value>
      <webElementGuid>4e28f2cd-0541-488f-8088-0027cbf06ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-light ') and contains(concat(' ', normalize-space(@class), ' '), ' dropdown-toggle ') and (@title = '')]</value>
      <webElementGuid>6344dde6-5c63-4801-a087-99f7a6141436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-light ') and contains(concat(' ', normalize-space(@class), ' '), ' dropdown-toggle ') and (@title = '')]</value>
      <webElementGuid>708ec103-0e85-4e15-9b87-9d10a08ec104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select an Assistant' or . = 'Select an Assistant')]</value>
      <webElementGuid>b6537b07-21c0-4611-932a-8511d70bdd07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
