<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_All</name>
   <tag></tag>
   <elementGuidId>e17564f0-e0ae-4f9c-8c4e-217a41094195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' va-chats-tab ') and (position() = 4)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.va-chats-tab:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;All&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1c38bde-263d-4a88-a11a-0c0cfae90846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c24ed10-4336-4296-86a4-926d77c70df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-chats-tab border-b-2 px-3 py-2 text-center font-semibold leading-tight transition-colors border-[#b80e74] text-[#b80e74]</value>
      <webElementGuid>af865bd1-cb73-4080-aa0c-98ade670f0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>6110b2ab-5020-419e-a99d-8bd2ff75fa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6953c2bd4e31fa2811a991bfe8a751b6</value>
      <webElementGuid>788ac06a-0f1c-46d3-9f47-d0d92e03a1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' va-chats-tab ') and (position() = 4)]</value>
      <webElementGuid>67ba1e66-84a1-41e6-9cea-920a09045d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' va-chats-tab ') and (position() = 4)]</value>
      <webElementGuid>baa29bd7-ecb8-4061-9c24-620f57caef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>332dbc1b-0b42-4057-b89f-2949a7d5df14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
