<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Assigned</name>
   <tag></tag>
   <elementGuidId>ecce5dfb-cd08-43ca-bc92-baf41cae9208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Open chats, Assigned']//h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Open\ chats\,\ Assigned&quot;] h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open chats, Assigned&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c9ac74f8-31d9-43d4-9e8d-3183f718c20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0</value>
      <webElementGuid>9df67fca-6e2a-4a79-81ec-5de4cc058bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assigned</value>
      <webElementGuid>cf6bd9dc-dd35-4fca-9486-c647fd4f309a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1c298e230ca21009648c9ae8deb48888</value>
      <webElementGuid>0723f725-3eee-4292-9089-b4f7826fbfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open chats, Assigned']//h3</value>
      <webElementGuid>9730ba61-ed2e-449a-92e4-868ff5090f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open chats, Assigned']//h3</value>
      <webElementGuid>99dc26a9-d686-4c2a-a2fd-3b532a8bf421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Assigned' or . = 'Assigned')]</value>
      <webElementGuid>31a5c010-2949-4042-b910-455414d7a5be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
