<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Unassigned</name>
   <tag></tag>
   <elementGuidId>88d8902e-3049-4e55-bd15-b58ab2afb85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Open chats, Unassigned']//h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Open\ chats\,\ Unassigned&quot;] h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open chats, Unassigned&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ec71b040-e700-4c39-b774-0f104fd87ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0</value>
      <webElementGuid>b1e9c83d-c5be-4fdf-ae89-1e3bd3043250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unassigned</value>
      <webElementGuid>7763a65f-e64a-4497-8469-bed9826cb5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-925d6eb0e6b8c81d8c2cd6fd6cbc46bf</value>
      <webElementGuid>7ffa75a3-fc79-4bc6-9c1e-0816ee7d120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open chats, Unassigned']//h3</value>
      <webElementGuid>6f572b1c-7968-448f-872a-d05b68707266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open chats, Unassigned']//h3</value>
      <webElementGuid>2c1649d0-6a80-44a6-9bc0-a75b18e91305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Unassigned' or . = 'Unassigned')]</value>
      <webElementGuid>9a6d4ddf-cbd8-4e18-b9c3-265f071d6ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
