<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>e83535e6-8893-45f8-9b86-59efa45a36c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/virtual-assistant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/virtual-assistant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0be3f7ba-1188-4850-bff4-5ba2c0bdc9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex items-center gap-2 px-3 py-2 text-[14px] font-semibold rounded-[5px] transition-colors no-underline text-[#4b4b4a] hover:bg-[#ffebf6]</value>
      <webElementGuid>68bff389-6de8-4ae1-81e1-ced8c6b67df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/virtual-assistant</value>
      <webElementGuid>19615386-c791-4491-b41c-381e8322c04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5678d85-a10d-411e-b28b-2b0469e48f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>82d660ec-af25-4cfd-a2b7-57c6bb421f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7ce433c723ab993aaeecde7146cd9e72</value>
      <webElementGuid>cc47d50b-996f-4e84-ba11-b5c743c4ae07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant']</value>
      <webElementGuid>1c8eab68-26bf-46f3-8596-a69d42f964ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/virtual-assistant']</value>
      <webElementGuid>f92112fe-8b4c-4a2f-9158-bb50ce2e2be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/virtual-assistant' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>4f738623-227c-415d-8c31-ee4fc6aeb324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
