<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_scheduler_viewNavigatorBlock_ctl00_BG_GTDBII</name>
   <tag></tag>
   <elementGuidId>3faf85b2-c540-4b1e-806d-d463d22fa105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dxScheduler_ViewNavigator_DownHover_Metropolis ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.dxScheduler_ViewNavigator_DownHover_Metropolis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;V&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d28026d7-ce4a-4a51-add1-5c2f6ffae63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxScheduler_ViewNavigator_Down_Metropolis dx-vam dxScheduler_ViewNavigator_DownHover_Metropolis</value>
      <webElementGuid>5b562c7b-3b5d-4565-96d7-951b967742de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-1USRw</value>
      <webElementGuid>03745303-7635-4c52-814c-d466412a9560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>b73e0cf1-dee0-4600-9564-e3521db6706f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scheduler_viewNavigatorBlock_ctl00_BG_GTDBIImg</value>
      <webElementGuid>513644fc-fdda-4e23-9534-2815e3a832cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>savedhoverstateitemsrc</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_110-1USRw</value>
      <webElementGuid>31cda038-e963-45d5-a5a1-b640e7fd61d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>savedhoverstateitemclassname</name>
      <type>Main</type>
      <value>dxScheduler_ViewNavigator_Down_Metropolis dx-vam</value>
      <webElementGuid>bf876e55-735d-440c-a848-5d742075ec82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f372c18e620c2852a73f1d84c6effc4c</value>
      <webElementGuid>f0e1f99f-bc4b-43ef-ab77-9c347079d2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dxScheduler_ViewNavigator_DownHover_Metropolis ')]</value>
      <webElementGuid>dafda737-81b5-421b-9004-cbc104e2ac08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dxScheduler_ViewNavigator_DownHover_Metropolis ')]</value>
      <webElementGuid>6cd241c3-6eeb-4ed4-bb12-261b6e0e0a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/DXR.axd?r=1_110-1USRw' and @alt = 'V' and @id = 'scheduler_viewNavigatorBlock_ctl00_BG_GTDBIImg']</value>
      <webElementGuid>4aa6b3e7-e8a3-4b7c-a1d9-fd9f1f0fa6d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
