<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ChiefComplaint</name>
   <tag></tag>
   <elementGuidId>496e8676-9c51-4837-9f8e-5992d4db4a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ChiefComplaint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChiefComplaint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Katalon Appointment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb66efeb-307e-46a2-95f5-87ee39331abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAreaHgtApptDetails</value>
      <webElementGuid>4bbf6750-6cba-4bb5-8895-6bc912adc468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>db67de09-d4ad-4b8e-8f66-beaf76baebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ChiefComplaint</value>
      <webElementGuid>7e6fe234-b16b-43fd-a9f0-444e73f2a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>APPOINTMENTDETAILS</value>
      <webElementGuid>485eaec7-f7a4-49a1-86d0-15440eb6594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Katalon Appointment</value>
      <webElementGuid>599100dc-f358-4624-84ed-a8e9d84e69b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChiefComplaint</value>
      <webElementGuid>1ada7e2d-a2fa-4eee-ab58-4f3610144594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChiefComplaint</value>
      <webElementGuid>ab8e867f-f717-45ef-9689-ad3a6a7199dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>AppointmentPopupChnaged()</value>
      <webElementGuid>cb9557f5-9d69-49cd-bcb6-ffc93cfd6c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>94a1ad9d-0cdc-4b1a-9e34-6b76b2a77f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2e30230-6ac6-494c-b673-6b185b8254ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>d6c181f5-c771-42c0-a3d1-fd9a5829840e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Appointment</value>
      <webElementGuid>9828641c-104a-42f1-a901-bb6c1f5e41e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-70ebe7e48a55f6bf0da734c3e2b73367</value>
      <webElementGuid>29c1a40f-f412-464c-bbc9-9bc3042695d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ChiefComplaint']</value>
      <webElementGuid>1505238c-3cd5-4217-bd50-c79eb91ca4f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ChiefComplaint']</value>
      <webElementGuid>f31d9789-9e92-4d93-9286-eba823cfc826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ChiefComplaint' and @name = 'ChiefComplaint' and (text() = 'Katalon Appointment' or . = 'Katalon Appointment')]</value>
      <webElementGuid>316843c7-bc8c-4379-bd35-1c61c903a733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
