<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modules</name>
   <tag></tag>
   <elementGuidId>713bdd51-6595-493a-a7ff-be8a13bb9e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-officeadminmainurl = 'Modules_menu/Home']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-officeadminmainurl=&quot;Modules_menu\/Home&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Modules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8b67e8c-6e07-4f66-a514-ddb112e0e2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6e3f3cca-bd16-48f6-b3ee-5e59d8b0e40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-officeadminelementtitle</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>4f71ca44-f081-4088-a920-ebcb7ee04fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SavePatientGeneralNotificationOfficeAdmin();SaveMaximeyesPatientPortalData(this);</value>
      <webElementGuid>30f05311-92ca-49c1-8a54-36436c8c204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-officeadminmainurl</name>
      <type>Main</type>
      <value>Modules_menu/Home</value>
      <webElementGuid>4034ddb5-8004-4825-8a3f-c343a81d58e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Office Admin > Modules</value>
      <webElementGuid>b6a2cb35-da4f-4617-93be-436ff26e0f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>c9d4fada-e2c6-4291-872e-3040383b0b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-45535d521066054bb96459da27c4c19d</value>
      <webElementGuid>44b469f5-344b-4a5e-8d65-99b698068232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-officeadminmainurl = 'Modules_menu/Home']</value>
      <webElementGuid>06b66f27-5d1d-42c1-a992-99d0c7f181c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-officeadminmainurl = 'Modules_menu/Home']</value>
      <webElementGuid>7caadb6b-5882-40fb-b69a-7c3bd864e8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Modules' or . = 'Modules')]</value>
      <webElementGuid>651c0a68-938f-4c11-bfc3-f9c09ce6f742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
