<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ui-id-20</name>
   <tag></tag>
   <elementGuidId>119fbed5-4ac3-4f77-a8a9-5040e319e594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminschedular ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.NevOfficeadminschedular</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Schedule&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aec99602-de43-4aaa-85aa-65da545d4edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Scheduler</value>
      <webElementGuid>4b9c8e6a-26d2-411d-b0bb-9a40332c2600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NevOfficeadminschedular ui-tabs-anchor</value>
      <webElementGuid>1c8b5755-f1a2-4352-a071-eb0db1310055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thirdnavigation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5294c0ab-ece7-45f6-8fbd-b9300406548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>../Schedule/officeAdminScheduleGeneralpage</value>
      <webElementGuid>10f03b26-a366-44bb-ad95-9afca1d471e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowOfficeAdminEncounterElement(this)</value>
      <webElementGuid>5a67c2bf-4c39-4c71-a13e-cd8b9d303715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>49f0a43d-d581-472a-96c7-043b1e539a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1ee4385c-bda9-41a2-8856-38483e0d2f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-20</value>
      <webElementGuid>ab913dfe-9bbd-4573-9ac7-98da6368fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule</value>
      <webElementGuid>23b5c139-8384-48ea-ad30-a654540c8b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e6f291e0a4757d56d519357101b3d24f</value>
      <webElementGuid>1f0593c8-0a0e-491a-9c7e-96c465bf5afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminschedular ')]</value>
      <webElementGuid>856cf1d7-4fc3-4b48-9d66-5862343c514a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' NevOfficeadminschedular ')]</value>
      <webElementGuid>c3fcbd68-163f-4c41-abca-9c01804695bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Scheduler' and @id = 'ui-id-20' and (text() = 'Schedule' or . = 'Schedule')]</value>
      <webElementGuid>3acbb325-ad8a-4532-a421-63abdfb50784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
