<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Available for Online Scheduling</name>
   <tag></tag>
   <elementGuidId>f6b3a387-5478-48ca-80b2-c1cb76453d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chkIsOnlineSchedule']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;chkIsOnlineSchedule&quot;] .icons span:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Available for Online Scheduling&quot;i >> span >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d10ed7d-7796-4422-aba0-eae7cfd10e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-checked</value>
      <webElementGuid>09c8885c-4e07-4a5c-935c-caf5bf627eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3b2f716f796e2714bc0cfb93241d3f6a</value>
      <webElementGuid>17e21b9c-db0c-4c60-bc08-c518a75d871a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'chkIsOnlineSchedule']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' icons ')]//*[(name() = 'span') and (position() = 2)]</value>
      <webElementGuid>5f9294ea-2d52-44f4-9111-dabfb06b2b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chkIsOnlineSchedule']</value>
      <webElementGuid>671a33d2-2c05-4491-a004-8a5716ad0f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
