<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Katalon Resource</name>
   <tag></tag>
   <elementGuidId>ac5f2604-53a7-468a-9562-0debf5dcf203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@role = 'gridcell')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.cursor-pointer[role=&quot;gridcell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Katalon Resource&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c817d451-4a9d-45bf-8bd8-e8e957d0daff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline cursor-pointer</value>
      <webElementGuid>42589d63-8ee1-44b3-bf46-82c888535ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac592614-6e7d-4977-9af7-10dcf423d50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0d0cda7b-b419-4845-8a58-e9ccc3b138ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d26bc776-bc18-47b9-86d3-f72a3742f800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0137cd2d-3e5d-442d-a9b4-46196152f4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Resource</value>
      <webElementGuid>602c8611-aac3-4c27-afb8-54e062d1de0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-998ffd9bb9fe7cdbd5f455cd5e0cf91a</value>
      <webElementGuid>465a58ad-7c72-48a4-a124-bb8e175269a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@role = 'gridcell')]</value>
      <webElementGuid>61aa5226-5763-459e-b73d-8c189ba05d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (@role = 'gridcell')]</value>
      <webElementGuid>dc068e49-ca3b-41c0-976a-1417243e4025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Katalon Resource' or . = 'Katalon Resource')]</value>
      <webElementGuid>39bb1c7f-dc55-4b1b-a667-7a7065354a63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
