<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_id</name>
   <tag></tag>
   <elementGuidId>c3a15f99-8289-470c-b05e-a93a8953c7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;gajakumara@first-insight.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5c559e9-aebc-4fff-806a-bb17b80633a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-medium text-dark</value>
      <webElementGuid>87a7fffd-def6-4bef-9fbe-7fa5a6364e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gajakumara@first-insight.com</value>
      <webElementGuid>f9d2a7fc-c1d3-4421-9f22-ea04c8316f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid min-vh-100 d-flex flex-column align-items-center justify-content-center bg-light&quot;]/div[@class=&quot;card shadow-sm&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;p-4 pt-0&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;bg-light rounded-3 p-3 border-0&quot;]/div[@class=&quot;fw-medium text-dark&quot;]</value>
      <webElementGuid>8b7d227e-49d0-45b9-a812-20bd30ce2e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div[2]/div[4]</value>
      <webElementGuid>61b6db9b-00a8-4dca-8af3-f251226487f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Email'])[1]/following::div[1]</value>
      <webElementGuid>6b51bf03-af85-4ac0-8b70-fd309f2832fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIC'])[1]/following::div[2]</value>
      <webElementGuid>424a23dc-a307-4dd9-9b57-63e4c9e4d279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your EVAA Products'])[1]/preceding::div[1]</value>
      <webElementGuid>f8ded4c0-de4e-4e58-b4c8-59683917d130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVAA Intelliscan'])[1]/preceding::div[3]</value>
      <webElementGuid>d7495bbc-df9b-4a26-a5c5-ac156eaa00c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='gajakumara@first-insight.com']/parent::*</value>
      <webElementGuid>40240dda-ca75-432e-b733-e08f2c7b0e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]</value>
      <webElementGuid>a434e2f5-b08b-4da3-9e25-b460cb645a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'gajakumara@first-insight.com' or . = 'gajakumara@first-insight.com')]</value>
      <webElementGuid>5d60889d-27f5-4a80-adc5-e27b52c2cb27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
