<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__privateStripeFrame7493</name>
   <tag></tag>
   <elementGuidId>a09ecf04-6bc5-494e-9b80-9bcd5d7f83fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = '__privateStripeFrame7493']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;__privateStripeFrame7493&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;__privateStripeFrame7493&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>37fd27cd-eeab-4169-8c84-b332f862177d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame7493</value>
      <webElementGuid>9d35c470-3d49-4c0c-a28f-b8b17e404928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>133d66cf-69aa-4e83-819f-b330cad2cdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a7348cb-cfda-4655-ade7-bd2177817862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b6ea2537-5eca-4aa3-9042-65ac33917c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6827d597-da49-415e-90df-776a31007ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *; publickey-credentials-get *</value>
      <webElementGuid>41ac9242-b343-41d8-8598-7716a9a22c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-payment-5e70424941e070347bdff8a73878e049.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%22444a5e8f-e2d5-4e61-9382-f19075c4453d%22%2C%22assignments%22%3A%7B%22elements_generic_skeleton_loader_v3%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-3072d895-9deb-406c-bf4e-5c5cb1399049&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;referrer=https%3A%2F%2Fpay.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController7491</value>
      <webElementGuid>bd9c25b9-c5a5-4599-8926-bdd0c8aee713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>179a22a2-7efe-4add-99c9-13e6f15d3e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2e15c5941faaaa9c93252a75b48cc272</value>
      <webElementGuid>10c3acaf-924d-4431-a98e-3b5a7a51b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '__privateStripeFrame7493']</value>
      <webElementGuid>dde2efbe-e6b6-4e5c-bceb-a6f2ef6b0e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Unified Admin/iframe_EVAA Payment</value>
      <webElementGuid>8e7cf516-f484-422f-a3f5-58dcb8804d17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '__privateStripeFrame7493']</value>
      <webElementGuid>ef85cf74-1467-4762-a062-faa0649afd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame7493' and @src = 'https://js.stripe.com/v3/elements-inner-payment-5e70424941e070347bdff8a73878e049.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%22444a5e8f-e2d5-4e61-9382-f19075c4453d%22%2C%22assignments%22%3A%7B%22elements_generic_skeleton_loader_v3%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-3072d895-9deb-406c-bf4e-5c5cb1399049&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;referrer=https%3A%2F%2Fpay.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController7491' and @title = 'Secure payment input frame']</value>
      <webElementGuid>59ac2ea7-266e-438c-976f-5801c5e50832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
