<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_24.00___privateStripeFrame4504</name>
   <tag></tag>
   <elementGuidId>93ae04b4-df7c-44e0-a09b-856620c0c4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame4504&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-element']/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;__privateStripeFrame4504&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3e860898-2893-4023-83ba-db106d048adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame4504</value>
      <webElementGuid>294ae9aa-1aee-4411-a89d-1b400b232473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f774a367-7ac8-4e88-99d9-ee16c444c048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14e3c94a-a6ef-457f-aa06-8bf7d3e92d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f6bec7c7-9485-4a4e-8542-fd39aeff4119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>612efb57-a143-4ed1-b559-853a8396cd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *; publickey-credentials-get *</value>
      <webElementGuid>bafc6852-71e1-4fcb-89ae-96bfaccec7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-accessory-target-b3679e3307e921d01de4b275d2b56b66.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%225df8371f-f1dc-47e2-b0ae-f752a66d37e4%22%2C%22assignments%22%3A%7B%22elements_accessory_frame_rendering_v5%22%3A%22treatment%22%2C%22elements_generic_skeleton_loader_v2%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-443a4b28-bd5f-4f01-86e3-007db8833876&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;accessoryCssUrl=https%3A%2F%2Fjs.stripe.com%2Fv3%2Ffingerprinted%2Fcss%2Felements-inner-payment-331768d3f27dae4befda60c96104723e.css&amp;referrer=https%3A%2F%2Fpay.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController4501</value>
      <webElementGuid>6d3bb40e-4420-4b94-94d4-e779cf183906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>8d903c99-08c0-46ba-ae98-638bf7defab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>ca838c8f-6994-42c3-9b66-f807193a22d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Unified Admin/iframe</value>
      <webElementGuid>7e4d59b0-3424-4eea-a68c-f547d2fb4a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame4504']</value>
      <webElementGuid>6bad15a1-13c2-4887-a646-76da5f96c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-element']/div/iframe</value>
      <webElementGuid>512b206a-8faf-4051-84f7-e1881f47a13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fa96cbbd-9d9b-4139-88de-a20df565cf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame4504' and @src = 'https://js.stripe.com/v3/elements-inner-accessory-target-b3679e3307e921d01de4b275d2b56b66.html#__shared_params__[version]=basil&amp;__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%225df8371f-f1dc-47e2-b0ae-f752a66d37e4%22%2C%22assignments%22%3A%7B%22elements_accessory_frame_rendering_v5%22%3A%22treatment%22%2C%22elements_generic_skeleton_loader_v2%22%3A%22treatment%22%7D%7D&amp;wait=false&amp;rtl=false&amp;publicOptions[layout]=tabs&amp;elementsInitSource=stripe.elements&amp;elementId=payment-443a4b28-bd5f-4f01-86e3-007db8833876&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_51SNAlT3tGsPcGpd44ADPXueehthbuUf3InoOLNkNu6oUs1SVyb7ktGdSjpXmHdzVCvojYKhr2pgxo5ls1E83fzse00WuoHDrcH&amp;frameMessagingStrategy=direct&amp;cryptoWalletDetected=false&amp;accessoryCssUrl=https%3A%2F%2Fjs.stripe.com%2Fv3%2Ffingerprinted%2Fcss%2Felements-inner-payment-331768d3f27dae4befda60c96104723e.css&amp;referrer=https%3A%2F%2Fpay.evaa.ai%2Fcheckout&amp;controllerId=__privateStripeController4501' and @title = 'Secure payment input frame']</value>
      <webElementGuid>56ddafa8-7659-4f06-802c-0498d92c9fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
