<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_closed-Saturday</name>
   <tag></tag>
   <elementGuidId>494642a7-523b-4ab7-8012-035f3b5eb817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='closed-Saturday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closed-Saturday</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closed-Saturday</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9d52d8e-c53f-41d7-8a5d-5131549371b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input</value>
      <webElementGuid>34dd5e85-878c-4635-889d-3890327162c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9db174ac-9819-4cc5-a774-9a8419af63f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closed-Saturday</value>
      <webElementGuid>2f30e61a-b483-472a-b0ed-7829fbed9cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closed-Saturday&quot;)</value>
      <webElementGuid>2a404361-8e05-4d5a-86f8-26291449594d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='closed-Saturday']</value>
      <webElementGuid>2de1359a-96c2-4b19-a65b-dc98eb968618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[4]/div/div/div[2]/div/div/div[16]/div/div[3]/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>5ab5068e-6c9f-4b06-a351-b66bd8c28dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>537231ac-cf15-4bfc-83a6-cbec27546d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'closed-Saturday']</value>
      <webElementGuid>df7c771c-2d7b-40a7-8ff6-f21c1ab693ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
