<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_evaas-iframeId</name>
   <tag></tag>
   <elementGuidId>7f58aad0-8146-4a68-953a-32d0006be75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#evaas-iframeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'evaas-iframeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#evaas-iframeId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9e0e5175-e6ca-4322-a33a-ca3cdfa38aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evaas-iframeId</value>
      <webElementGuid>2079c280-4493-4fc0-9a90-89fccd41f129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>882a75b6-3032-4be8-b7b3-d6914494c8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true</value>
      <webElementGuid>c0a8e94b-869a-447b-a24d-59eee9604b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-visible</value>
      <webElementGuid>569782bf-9711-413f-a511-e1f722514311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5cc6c57ae394525d64f02ff90b040411</value>
      <webElementGuid>b81c1694-54d7-47fd-a6f0-4208a183cf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>f3dd5324-02ba-4d79-90f3-103d4bbe64da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>f7eee9e5-e3fb-4b5c-974d-0d661a70e163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'evaas-iframeId' and @src = 'https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true']</value>
      <webElementGuid>2f849031-fee2-479d-9b53-e0d77428ee8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
