<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MaximEyes</name>
   <tag></tag>
   <elementGuidId>68ec10c9-6e86-4a2b-83b2-2398341da0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'loginwithmaximeyesClick()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;loginwithmaximeyesClick\(\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Maximize Icon MaximEyes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee02b070-05c5-4cc5-a8c5-f05a9c89dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae165f2c-b92c-4da3-9ada-299050bbbc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-secondary</value>
      <webElementGuid>ac87c38b-a236-4d2e-b4bd-741aafc6d262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loginwithmaximeyesClick()</value>
      <webElementGuid>cfb2e26a-65a4-4713-a7e5-c9172ffcc2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  MaximEyes</value>
      <webElementGuid>98cad0c7-2ff1-469d-b6c9-bf2e164a6d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6dc0eadc03f960f22d4e025df5cfcfab</value>
      <webElementGuid>994cd791-521c-480b-9557-2bdf71ef14c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'loginwithmaximeyesClick()']</value>
      <webElementGuid>3065f317-7896-4c36-bbac-0e882f3990d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'loginwithmaximeyesClick()']</value>
      <webElementGuid>932a6011-2a32-44f3-ba68-2323a4a5f37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  MaximEyes' or . = '  MaximEyes')]</value>
      <webElementGuid>90a2cc4e-fd16-4055-843e-7daf5f0c382f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
