<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_None</name>
   <tag></tag>
   <elementGuidId>52286616-91ac-4f92-8efe-02e87553f8d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.whitespace-nowrap.text-sm.\*\:data-\[slot\=select-value\]\:flex.max-w-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:has-text=&quot;None&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d81c4c1f-54ad-4a35-8085-3465dd5ad8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74274786-7282-45df-92b9-b822bfe5a952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b8181ba5-81d5-4963-9933-f395993ca622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r4h:</value>
      <webElementGuid>c3e7b797-cd34-4a18-86da-c350adc46b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b70c0d10-3289-4c39-b6ac-21954246e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e79c3dbf-fde9-4296-8888-d4bfd84e835d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>76edf067-4576-4b11-a5f0-d4222d266b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>4ec123ef-d454-4a25-a559-153a0989691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>select-trigger</value>
      <webElementGuid>4311c5a6-8ab6-4cbf-83f9-28064d175b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>87b73605-7f95-45ee-ab17-1bc8fd87d665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-[#d0cec3] data-[placeholder]:text-[#6b7280] [&amp;_svg:not([class*='text-'])]:text-[#4b5563] flex items-center justify-between gap-2 overflow-hidden border px-3 py-2 text-sm text-[#1a1a1a] whitespace-nowrap transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-[#b80e74]/30 disabled:cursor-not-allowed disabled:opacity-50 disabled:text-[#9ca3af] data-[size=default]:h-9 data-[size=sm]:h-8 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center *:data-[slot=select-value]:gap-2 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 w-full max-w-md !rounded-[13px] bg-white</value>
      <webElementGuid>9aebe64b-41fb-46de-8de0-3e97995484d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>30cfdc63-5b7e-4c62-865c-21725ef160c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ce5b8501c5c2127fa8be5b2f76ede005</value>
      <webElementGuid>c11fa211-2fdc-4745-b57b-9fb6ade22d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      <webElementGuid>84ce8824-5ecb-4f90-bf79-c5c01591bfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and contains(concat(' ', normalize-space(@class), ' '), ' max-w-md ')]</value>
      <webElementGuid>8f90061f-7dcd-46d1-a318-c6d5f0ff7a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'None' or . = 'None')]</value>
      <webElementGuid>a2b95ad0-5391-446b-ba0a-e03b7c0b5e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
