<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Royal Magenta (RM)</name>
   <tag></tag>
   <elementGuidId>66fe0035-904b-4f3b-b9fb-66aae1f60fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'div') and (position() = 6)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex '))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(6) .whitespace-nowrap.text-sm.\*\:data-\[slot\=select-value\]\:flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:has-text=&quot;Royal Magenta (RM)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ac3d42d-b034-419a-81e0-b9ba5ae7ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67c7173b-6383-4dd7-b593-974d30bafca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>27b12387-db98-4ec9-babc-cf446d3e419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r4g:</value>
      <webElementGuid>870525d4-2da3-498b-b319-07c2e315641d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6466f98-3e51-4152-888f-3dd0c7ad0564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a7b87aa6-da95-4ae1-bd39-c7cded0cfee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>9214f1bb-4c4b-4052-82bc-160a505df9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>9c9d58b7-a51b-4221-9240-4835b36bd20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>select-trigger</value>
      <webElementGuid>db901eea-68d5-4700-9f89-d1069a5731f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>054ac86d-e9db-4a06-93ca-d7b264892678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-[#d0cec3] data-[placeholder]:text-[#6b7280] [&amp;_svg:not([class*='text-'])]:text-[#4b5563] flex items-center justify-between gap-2 overflow-hidden border px-3 py-2 text-sm text-[#1a1a1a] whitespace-nowrap transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-[#b80e74]/30 disabled:cursor-not-allowed disabled:opacity-50 disabled:text-[#9ca3af] data-[size=default]:h-9 data-[size=sm]:h-8 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center *:data-[slot=select-value]:gap-2 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 w-[min(100%,240px)] !rounded-[13px] bg-white</value>
      <webElementGuid>6c7edd81-28c2-42b1-8e20-9e11a827d54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Royal Magenta (RM)</value>
      <webElementGuid>43a1c5b5-a694-4972-a935-1238e93b5ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-308c0277c276f26a151af67f4e088684</value>
      <webElementGuid>731c8508-aac1-4ca0-abbb-e69a83392c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 6)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex '))]</value>
      <webElementGuid>ca6b6d46-5359-4484-9c0c-083a4739bb5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 6)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex '))]</value>
      <webElementGuid>39f7ddc0-c9e3-402c-bee4-b0a142b10815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Royal Magenta (RM)' or . = 'Royal Magenta (RM)')]</value>
      <webElementGuid>b9086114-b749-4022-8785-773237cb7158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
