<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_radix-_r5e</name>
   <tag></tag>
   <elementGuidId>65109227-fd49-40ae-a445-b413d71b945e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'radix-:r5e:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;radix-\:r5e\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sound 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d1576ff-4256-4010-8a79-07f169827316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d9728995-cc62-4122-a058-f0ffbb708675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-:r5e:</value>
      <webElementGuid>27b3f314-558e-48b7-834b-22405e05556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f5e91bb-9666-4f1f-af45-6a9531c80669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>ab0cbb9e-2fea-40f1-b3c5-045dfc463ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fca26706-58eb-499a-9c58-881ea9a974fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>select-item</value>
      <webElementGuid>7cebd331-6f2a-4a72-8971-0f7788281fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex h-[34px] w-full cursor-default select-none items-center gap-2 !rounded-[16px] bg-white py-[5px] pr-8 pl-3 text-sm text-[#1a1a1a] outline-none hover:bg-[#F6F6F1] focus:bg-[#EFF4F8] focus:text-[#1a1a1a] data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[state=checked]:bg-[#EFF4F8] [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0</value>
      <webElementGuid>34e507ee-2129-4db4-b3ba-821eb32af59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sound 1</value>
      <webElementGuid>18003c32-999b-47b1-a2c7-b79cae2f9a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c0465aecb7add3adc28ebfec9570b450</value>
      <webElementGuid>d59f43b4-0987-45eb-82cf-59f010ed8a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r5e:']</value>
      <webElementGuid>49994d2e-04e7-4964-8bf0-e8e25717891f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r5e:']</value>
      <webElementGuid>bad921c7-11d8-4812-85f3-ee8b5c3ede71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sound 1' or . = 'Sound 1')]</value>
      <webElementGuid>8ad4135b-3922-4e23-909f-a828c6274dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
