<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address (Line 2)_PL_Main_Line2_c84d6056</name>
   <tag></tag>
   <elementGuidId>14150402-7702-4bc4-afb5-4c38025951a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PL_Main_Line2_c84d6056']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PL_Main_Line2_c84d6056</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;Addresses\[0\]\.Line2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eeedd9e-7c6c-4de3-b2d4-9f6716f263f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PL_Main_Line2_c84d6056</value>
      <webElementGuid>1426c63c-6db0-4be2-808f-3afdd71b3f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>55dfa096-3767-48f1-9de1-59351c63beb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>335187ff-bcfb-437d-9233-fec8db49f17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4030ae2-a133-405e-bc83-825a32f4ca24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].Line2</value>
      <webElementGuid>ae6d6907-4614-458f-92d1-52f175a0bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f33d45b8-3e11-42cb-9392-c5529c9b14d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>36a6a88f-4141-4691-8b9d-3b8990e4ed7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PL_Main_Line2_c84d6056&quot;)</value>
      <webElementGuid>9882345a-d8a4-408b-8a27-3d74a2b86d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PL_Main_Line2_c84d6056']</value>
      <webElementGuid>1c2dd102-ff2d-4027-a5f8-33798ee552c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Main']/div[2]/div/span/input</value>
      <webElementGuid>1565b457-f663-47b0-833a-f02e5fc2a72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>f2c43c19-b18e-4998-8f00-d69de3d32602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PL_Main_Line2_c84d6056' and @name = 'Addresses[0].Line2' and @type = 'text']</value>
      <webElementGuid>a42e66ca-42f0-43b8-ba4f-8628a456bd83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
