<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_PR_Info_Address_Main_ZipCode_c79f50</name>
   <tag></tag>
   <elementGuidId>7ad23a72-33c3-42b3-bc8d-2493bd45835f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PR_Info_Address_Main_ZipCodePlus4_c84d6056']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PR_Info_Address_Main_ZipCodePlus4_c84d6056</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_Info_Address_Main_ZipCodePlus4_c84d6056</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20847c30-b8c5-4c7c-8273-8be5cab45e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_Info_Address_Main_ZipCodePlus4_c84d6056</value>
      <webElementGuid>6832b9e5-7476-4a3e-9556-75df50f3698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>679a2499-1732-4029-a48e-54756f933c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ZipCodePlus4</value>
      <webElementGuid>b46a4aa5-0aef-4100-b725-1e21597fa4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>ZipCodePlus4</value>
      <webElementGuid>b554e201-0e41-4dc7-bac1-fc144087d5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>bd9ccb2e-ba05-4832-87c4-0e9d245a911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d223dfcb-8f8d-4a41-be05-dca3f9e542ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3e22feb6-3d0c-4ff2-98d7-23811870b201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].ZipCodePlus4</value>
      <webElementGuid>6e50b1be-06c2-4fd1-a38d-52817a0205ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearStateZipCityPracticeLocation(PL_Main_StateId_c84d6056, PR_Info_Address_Main_ZipCode_c84d6056, PL_Main_ZipCodeId_c84d6056, PL_Main_CityName_c84d6056)</value>
      <webElementGuid>067ebadf-873b-4b67-b29e-636d69a29290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc82db06-c07e-4223-96ab-984420dc1817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>9a2e90a7-0ec2-47a7-80fc-ddc910921760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PR_Info_Address_Main_ZipCodePlus4_c84d6056&quot;)</value>
      <webElementGuid>f96c674c-38e1-4591-b428-8141f0fb2cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PR_Info_Address_Main_ZipCodePlus4_c84d6056']</value>
      <webElementGuid>fd2fed92-96bd-4c6f-901e-a23d5eec24c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Main']/div[3]/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>cb171209-6c2c-482d-8527-848aef3b4b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>3a3fe8e8-0821-440a-8fff-c30e501ede8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_Info_Address_Main_ZipCodePlus4_c84d6056' and @name = 'Addresses[0].ZipCodePlus4' and @type = 'text']</value>
      <webElementGuid>685c909b-45b8-48a4-9d4b-edd94ce979e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
