<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_PR_Info_Address_Main_ZipCode_aa58c9</name>
   <tag></tag>
   <elementGuidId>c0eb28ff-9543-41c7-adb6-53e54cbc76dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zipcodeID5_Main']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PR_Info_Address_Main_ZipCode_c84d6056</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PR_Info_Address_Main_ZipCode_c84d6056</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cb126d1-7b1e-468e-b777-7c36b510ba0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PR_Info_Address_Main_ZipCode_c84d6056</value>
      <webElementGuid>f0905467-21cc-4b19-a7fe-0c042425ccbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>d21452ec-97d0-4467-8591-cd1672b253a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ZipCodeString</value>
      <webElementGuid>8ea464c4-733c-4ef5-8143-dd24ac4d21f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>ZipCodeString</value>
      <webElementGuid>01ec39fb-30c9-4ac8-bf3b-40d49c2ac527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nochangeevent</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>e743c869-f66f-43e8-9a0f-e634ac355a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>40007f40-b4c4-47bb-bbf5-da85e9331994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bab66793-bc4e-4e5d-a12a-107766df699e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].ZipCodeText</value>
      <webElementGuid>842b6bb9-855e-46e1-89cb-6fa213797774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearStateZipCityPracticeLocation(PL_Main_StateId_c84d6056, PR_Info_Address_Main_ZipCode_c84d6056, PL_Main_ZipCodeId_c84d6056, PL_Main_CityName_c84d6056)</value>
      <webElementGuid>c712e655-4206-48bd-be13-10567f49e2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d89ee4b8-4a6c-433c-a1ad-d3c2623fc826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>d28ec1a0-e308-449d-ad87-d1094705849e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PR_Info_Address_Main_ZipCode_c84d6056&quot;)</value>
      <webElementGuid>c41c6f22-372f-47a8-bd43-e4d20416d003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PR_Info_Address_Main_ZipCode_c84d6056']</value>
      <webElementGuid>36e0497f-0c01-4020-9739-7e33c0f8ab6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zipcodeID5_Main']/input</value>
      <webElementGuid>9ec2091e-8ae1-442f-bda3-4d294aca3e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>c2ced32f-be36-4d96-8323-91534a8f2e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PR_Info_Address_Main_ZipCode_c84d6056' and @name = 'Addresses[0].ZipCodeText' and @type = 'text']</value>
      <webElementGuid>76593771-928c-48d9-b833-77edad60c420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
