<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax_PL_Main_Fax_c84d6056</name>
   <tag></tag>
   <elementGuidId>ce292b48-eb34-44e3-ac5b-678597d0ccde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PL_Main_Fax_c84d6056']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PL_Main_Fax_c84d6056</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PL_Main_Fax_c84d6056</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>768c8355-39c2-424e-a49c-2ce42e69d9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PL_Main_Fax_c84d6056</value>
      <webElementGuid>147d1a99-7701-42cb-8a55-b5474636817b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45275835-1f08-4573-8c78-a9ee2b71d8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Fax is not valid</value>
      <webElementGuid>2b325eb3-f7cb-412c-be60-992e05f9c78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(\([0-9]{3}\) ([0-9]{3})-([0-9]{4}))|(\([_]{3}\) ([_]{3})-([_]{4}))$</value>
      <webElementGuid>4f1b1108-c20d-432c-897a-e289cec34735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].Fax1</value>
      <webElementGuid>c1e5fea6-acb1-49ed-8bfc-88962971d73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>092147f8-d8d1-4353-b1a3-f379d8ae0ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>c2e94860-bb52-4258-aae1-f19fd2823d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PL_Main_Fax_c84d6056-error</value>
      <webElementGuid>c177ba5f-f72c-4545-a5c8-f3ad17b0c559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>ad4b9fa0-2c05-40ad-aa2f-16955c1772f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a707d34a-d5bf-4506-adcb-49cd024558ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>92d76b23-d35d-4183-9188-ebb74a25f5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PL_Main_Fax_c84d6056&quot;)</value>
      <webElementGuid>ba5e5f69-753a-4d99-a38d-315159cffc57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PL_Main_Fax_c84d6056']</value>
      <webElementGuid>539da376-ee58-49cb-98b8-4e994aeedbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Main']/div[4]/div[2]/span/input</value>
      <webElementGuid>038a09ba-5432-4491-8eba-50b6da1e74a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span/input</value>
      <webElementGuid>d64168e8-6188-46ce-bc08-43df76944a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PL_Main_Fax_c84d6056' and @name = 'Addresses[0].Fax1' and @type = 'text']</value>
      <webElementGuid>55bb2b1a-7eb4-453b-9c36-a9883cd2eeca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
