<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ext_PL_Main_PhoneExtension_c84d6056</name>
   <tag></tag>
   <elementGuidId>8b2c4006-b7b0-4235-b264-d507abe8c970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PL_Main_PhoneExtension_c84d6056']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PL_Main_PhoneExtension_c84d6056</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PL_Main_PhoneExtension_c84d6056</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bd2d7f9-5bae-49cb-b2ed-3740be934bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PL_Main_PhoneExtension_c84d6056</value>
      <webElementGuid>01bf71a9-4a0c-4973-b062-456d09503798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>19ebfad3-67c6-41cf-b221-9497d0a6b70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Addresses[0].Phone1Extension</value>
      <webElementGuid>bbbcd2f5-0e1d-4d64-975d-63d092fe34b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>numericInputOnly(event)</value>
      <webElementGuid>f72da554-4052-4ce0-b5ca-fac2d7ebc4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be0b67e3-5c33-44a8-8044-2289d5dc9548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>83b24523-50f8-41ea-93e8-b8584752b1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PL_Main_PhoneExtension_c84d6056&quot;)</value>
      <webElementGuid>d5887892-e2e4-44fe-8e0b-92cdbbdb26ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PL_Main_PhoneExtension_c84d6056']</value>
      <webElementGuid>c5ed3369-0fde-4d7e-a1c6-c57db993c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Main']/div[4]/div/div/div/div[2]/span/span/input</value>
      <webElementGuid>594a893d-c3c7-44d2-ab11-c1b8a78ee33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>2127032e-553d-4ecb-816d-46e5f0d85e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PL_Main_PhoneExtension_c84d6056' and @name = 'Addresses[0].Phone1Extension' and @type = 'text']</value>
      <webElementGuid>b73c1d23-3c9e-40f5-a834-36d55a967ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
