<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Name DBA_txtBusinessNameDBA</name>
   <tag></tag>
   <elementGuidId>112dd5b9-6e4b-4dda-9977-c3ec5bef2da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBusinessNameDBA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtBusinessNameDBA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtBusinessNameDBA</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>481e3e85-1260-4c00-a3ec-4a83ab3e4bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBusinessNameDBA</value>
      <webElementGuid>a83471cb-6451-420b-bba0-7f3ab43e78cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>916e1eb0-eda3-4867-b870-c214e9a25043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PracticeBussiness.BusinessNameDBA</value>
      <webElementGuid>8b6ba573-c484-407c-a205-6ce339381033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92ef99ed-2c30-4dd6-964c-0340fd5ff582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>4c20f3b6-ad44-4995-92d4-5206efdae0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBusinessNameDBA&quot;)</value>
      <webElementGuid>2ee519df-88ce-4aa3-b91e-6b2fb0b29200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBusinessNameDBA']</value>
      <webElementGuid>cb1957d0-f1a0-41c4-9755-3153c0037b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewPBDiv']/div[3]/div/span/input</value>
      <webElementGuid>65501bb9-63cc-4190-8a15-9b4c806c1c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>16eb40d4-98f5-4462-a802-6bf980386021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtBusinessNameDBA' and @name = 'PracticeBussiness.BusinessNameDBA' and @type = 'text']</value>
      <webElementGuid>a8dd69bd-d26e-4d78-9d2a-9c51b6bb69ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
