<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SHOW_INACTIVE_Providers</name>
   <tag></tag>
   <elementGuidId>cb6ca2c3-79fb-4f10-8ca9-c72722a80684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SHOW_INACTIVE_Providers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'SHOW_INACTIVE_Providers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show Inactive&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>930deaf1-67a1-488f-90c3-109318041cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>05cf9882-5f44-4864-9976-7c9f5fab9a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5a7b6986-fe1c-4e76-8972-ee8318d58b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SHOW_INACTIVE_Providers</value>
      <webElementGuid>9ae8b931-793b-41cb-b8db-8d67a87dfd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SHOW_INACTIVE_PROVIDERS()</value>
      <webElementGuid>09038970-9371-4a8f-9728-ea5b0a3e8478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox</value>
      <webElementGuid>6509a4b3-a26d-4f0e-be43-5b1a45f13fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a7fe0687b3c55afcbadf71295a0b60c8</value>
      <webElementGuid>5328d866-3f94-4fc3-809c-374d8a4a7e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'SHOW_INACTIVE_Providers']</value>
      <webElementGuid>26bea736-74cb-47e1-bed8-84bc5e21005a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'SHOW_INACTIVE_Providers']</value>
      <webElementGuid>94ade807-bde4-42cc-9a06-919ee4ddda14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SHOW_INACTIVE_Providers']</value>
      <webElementGuid>29cc16e4-edb5-4bc4-a7b3-ae276d7c8e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
