<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_evaas-iframeId</name>
   <tag></tag>
   <elementGuidId>7e2966ff-1027-4277-bd2d-d84dd6fbe74c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#evaas-iframeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'evaas-iframeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#evaas-iframeId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>28f7ec65-d210-4872-8f6f-3aca32673856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evaas-iframeId</value>
      <webElementGuid>4e0e538b-1a79-4cd2-9f77-1ecc22660cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>1559fd64-9ffe-41ef-ad5e-b7c0a70fa0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true</value>
      <webElementGuid>29791af6-0bb9-4821-ab91-1c69884ebd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-visible</value>
      <webElementGuid>84aa25ad-aad0-4d3a-bbed-2abc48c7872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5cc6c57ae394525d64f02ff90b040411</value>
      <webElementGuid>b33dc670-c3bc-4489-bf9c-8a37e40bc704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>78aee531-2f0b-4571-99d0-593c365ad462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>a019dc60-ec5f-4860-b3ac-6a9ab0541aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'evaas-iframeId' and @src = 'https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true']</value>
      <webElementGuid>22fd8ba9-1e4f-471c-9f24-24392a7de13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
