<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otp-0</name>
   <tag></tag>
   <elementGuidId>a76e6a7f-b96d-4c06-ab86-d568814f0031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[autocomplete=&quot;one-time-code&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@autocomplete = 'one-time-code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#otp-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55bbcafa-128a-4478-b7dd-daa1c9ae076f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-0</value>
      <webElementGuid>8f7d9347-f0a3-4099-8549-4eeea65cab5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-otp-digit</value>
      <webElementGuid>9ea9adb7-a996-4ef0-b485-eda56e0eaa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d41ea4ff-953f-4d78-811e-d07667a6f112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>42137c02-dfd8-44d2-8023-dcb2c87f5a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>86f0958e-e224-4109-9199-6b573cb53412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9bb45acf50990a14b10a63c07c2b67bf</value>
      <webElementGuid>c55a984b-a88b-4506-8945-bb8eebf449b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@autocomplete = 'one-time-code']</value>
      <webElementGuid>f1ae47fd-680b-4df5-96fe-d221f291c292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/No Slots/iframe_evaas-iframeId</value>
      <webElementGuid>fba5cdb0-c049-4f58-94a0-6c0e53328139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@autocomplete = 'one-time-code']</value>
      <webElementGuid>9d891135-9a7e-44fc-ba0a-125aed633066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp-0']</value>
      <webElementGuid>5295a329-9033-4a93-b759-ab6262b04229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
