<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otp-1</name>
   <tag></tag>
   <elementGuidId>63ad5b35-63c8-457f-ade2-98bd94928d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;&quot;]:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@value = '') and (position() = 2)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#otp-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea77b490-fd26-4b5c-8e70-6f778c81783c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-1</value>
      <webElementGuid>b413d645-b061-470c-8721-72ef64c62195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-otp-digit</value>
      <webElementGuid>9f0cee30-9f40-4f93-afb2-9e6d51f96a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad073407-4a32-4f64-afff-73a35c9eb62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>21910b3c-21ec-40cb-a98d-a87f970a046a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a08b22d-b28c-4b95-af65-fcd18be1ecb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4f8bfd6096351b8d72d60243d89a33ee</value>
      <webElementGuid>d69f3241-e8d2-480d-9a33-d6be67962c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 2)]</value>
      <webElementGuid>0ced18ed-9bfd-4a71-a324-f23bc6e25f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/No Slots/iframe_evaas-iframeId</value>
      <webElementGuid>090562f8-2f32-4dc7-860b-a96ca78134cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 2)]</value>
      <webElementGuid>9741c3c7-6c55-45fb-9dc1-d3f66a8d71bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp-1']</value>
      <webElementGuid>6163ccf6-f5e3-45f0-982e-8cc1e3712886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
