<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Location</name>
   <tag></tag>
   <elementGuidId>358c22be-68e1-4cec-babb-26cd70e55d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;location&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Location*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a1779e38-b133-40a0-9639-b9f42829968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-label</value>
      <webElementGuid>d77b1150-76b5-4a93-bde7-42f39b0fa93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>7979376d-8e91-4fc5-896f-893dd273588b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Location*</value>
      <webElementGuid>f1006138-7e42-4033-985e-0d97c245d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fd2e94d87e6155e5f43e77c39485549f</value>
      <webElementGuid>4b615bc3-3c3f-4a16-8356-c7848d0ac0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'location']</value>
      <webElementGuid>141938f3-60d6-471e-9e4a-421647abccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/No Slots/iframe_evaas-iframeId</value>
      <webElementGuid>541ad8be-801e-4531-99ea-71ed018a675e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'location']</value>
      <webElementGuid>73d445d3-2bc9-4bc7-a84f-5482e4a8c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Location*' or . = 'Location*')]</value>
      <webElementGuid>4ed030d5-cb47-4d3b-9714-f229b1c3f6e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
