<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Provider</name>
   <tag></tag>
   <elementGuidId>ad8494a1-e38e-4ea8-b2c4-a52de36615da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;provider&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Provider*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6ae8d72c-79c0-4d85-b61a-7f919f0bab3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-label</value>
      <webElementGuid>6bb0f6e2-10f1-44a5-aefa-96ca69b7e65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>provider</value>
      <webElementGuid>a8cae0ab-64c3-4d24-9ee0-8868a7380239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Provider*</value>
      <webElementGuid>eab9b521-60de-4849-abd4-aa2f2bc50fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aaf89c6e0de284215bda9564eaa514e7</value>
      <webElementGuid>b73e8a00-7468-4638-8ec6-b77427e38e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'provider']</value>
      <webElementGuid>f443b39c-ccd9-427a-a8f4-83d31d9a2594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Reschedule Appt/No Slots/iframe_evaas-iframeId</value>
      <webElementGuid>a5b256a9-ee6c-4ee1-9f65-05052007e900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'provider']</value>
      <webElementGuid>748f8544-d701-40fd-8ca7-1c60c0d2d9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Provider*' or . = 'Provider*')]</value>
      <webElementGuid>84d556df-27ce-4375-ac67-763170f8a682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
