<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Providers</name>
   <tag></tag>
   <elementGuidId>b3752037-61d2-417b-b98c-bb0059ae7bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Fees Management'])[1]/preceding::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Providers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53240cb0-380e-4c96-befc-bc3d1827adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectorForGoogleAnalytics NevProviders ui-tabs-anchor</value>
      <webElementGuid>95343ba7-72fc-4577-ba5b-fae31a5cc2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Providers</value>
      <webElementGuid>c3b628e3-172f-4c39-bd99-17746e3f6280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>../Providers/GetAllProviders</value>
      <webElementGuid>ef91202f-8667-422c-9b33-a57b8362f5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowOfficeAdminEncounterElement(this);</value>
      <webElementGuid>b0148da2-f8b5-4b5a-8a19-09d052740095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>52e95121-21de-4ffc-934a-1bad4e95e7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d5ba3e4d-95cc-4da0-802f-206318acce0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-20</value>
      <webElementGuid>688a7ab4-0702-47e4-926a-fe35adfa207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Providers</value>
      <webElementGuid>7de6caf9-56c0-4f00-a51c-b542c96aeb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-20&quot;)</value>
      <webElementGuid>1aa72f57-34f4-4cfc-8875-020118f16a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-20']</value>
      <webElementGuid>fb668ec0-01f0-4965-b219-3cd752e5d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Business_Details_menu']/ul/li[4]/a</value>
      <webElementGuid>8fdd92bf-f4ec-4514-8311-aaa66c384abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Providers')])[2]</value>
      <webElementGuid>975af6f2-a6a0-4594-a3f7-a4dff8ee618d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facilities'])[1]/following::a[1]</value>
      <webElementGuid>9e7eece1-c7cb-4472-bc09-2b7942347ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/following::a[2]</value>
      <webElementGuid>c8fd8f76-7aa5-41ec-91ef-41fe008deb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users &amp; permissions'])[1]/preceding::a[1]</value>
      <webElementGuid>12e1179b-e303-4bde-8688-010679f0c080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fees Management'])[1]/preceding::a[2]</value>
      <webElementGuid>f30d8ff3-7a94-438e-90aa-a840af6cf18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Providers')]</value>
      <webElementGuid>0f750e6a-e1bd-463e-ac10-c2d086e717d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>ba4d5b95-4969-48d4-bd08-5b25defd240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Providers' and @id = 'ui-id-20' and (text() = 'Providers' or . = 'Providers')]</value>
      <webElementGuid>6dbf4d1d-da92-4450-a825-e98d28701468</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
