<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SHOW_INACTIVE_Location</name>
   <tag></tag>
   <elementGuidId>7e86173f-548e-4087-a058-5a0b9a08c171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SHOW_INACTIVE_Location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'SHOW_INACTIVE_Location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;  Show Inactive |&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>064018e8-52e4-443b-85ad-8bb5b600f02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a13d85e7-1923-4738-8e03-ba330f54d26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>faf743d1-a57a-4371-a62b-b647da41e41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SHOW_INACTIVE_Location</value>
      <webElementGuid>4a295b43-0c31-4da8-94ee-0e0b1bbe59e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SHOW_INACTIVE_LOCATIONS()</value>
      <webElementGuid>e40be7b8-5cda-4776-8eac-373151e77edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox</value>
      <webElementGuid>24df2c61-90e7-4ac6-a2d4-f915ebdc5903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cfd210003295e8185af391e712d891d7</value>
      <webElementGuid>9ce47c0b-2d61-4f3a-9415-797b95336723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'SHOW_INACTIVE_Location']</value>
      <webElementGuid>c03b0c7c-bb9c-4cbe-a6cd-96e40f57ea46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'SHOW_INACTIVE_Location']</value>
      <webElementGuid>9a56d9d8-d09a-4d52-b017-e5e9aaa92846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SHOW_INACTIVE_Location']</value>
      <webElementGuid>33b47c85-60c3-4431-b407-f52f99a950bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
