<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aetna-Back-20260802164721630.png</name>
   <tag></tag>
   <elementGuidId>de4df7f2-feb9-42f4-bd63-4ee3262434bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedGridTR ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.fixedGridTR:nth-child(2) .underline[data-donotdisable=&quot;true&quot;][data-prevent-remove-onclick=&quot;true&quot;][data-donotremoveclick=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Aetna-Back-20260802164721630.png&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25602c34-44db-469b-99f8-4c1211699fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prevent-remove-onclick</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16c0b411-1d10-4882-b097-2c43223ea597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-donotremoveclick</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73fd148c-78e1-433f-8f5b-db2e4cd0a83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-donotdisable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30dc7c3a-6b95-4776-970a-72ab22f0a050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>573fc024-67e5-40dc-81d8-1e3073fd07e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aetna-Back-20260802164721630.png</value>
      <webElementGuid>1a1208d5-1677-4b8a-8a8a-8484776d52db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a28d01a6ac493e2dcb0529fa63b2d348</value>
      <webElementGuid>7adff6f5-6785-4657-929f-9e1949e8d7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedGridTR ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      <webElementGuid>a9bfa5cd-6d7c-4fd6-b866-d9e7edd85378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedGridTR ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@data-donotdisable = 'true') and (@data-prevent-remove-onclick = 'true') and (@data-donotremoveclick = 'true')]</value>
      <webElementGuid>5c686160-26c6-4d52-a9a8-7d3b5fe3158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Aetna-Back-20260802164721630.png' or . = 'Aetna-Back-20260802164721630.png')]</value>
      <webElementGuid>ee3f9311-2b05-4365-9c2f-310ca495bcc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
