<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name</name>
   <tag></tag>
   <elementGuidId>af71b105-0fa8-4807-9549-f9e49bec138b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_FirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InsurancePlanDetails_InsurancePlanDetails_FirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02a3d1b8-a996-429d-8c4f-4de90721e573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input valid</value>
      <webElementGuid>1534abb6-ecbb-404c-915e-1748e135405c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>123137dc-66f1-4e41-a62d-70ee0c1fc92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInsurance.PlanDetailsListItem</value>
      <webElementGuid>e0ff49bf-fdb0-4374-9478-fd7bff0e4a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>rgb(224, 244, 153)</value>
      <webElementGuid>7bb4d2ed-9ff1-428b-b1ff-338960656632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Insurance</value>
      <webElementGuid>97e5f8f3-2b98-4770-b1e9-bf90a40110af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66f1a782-1eb7-48c1-bd01-196b355d85ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>QA</value>
      <webElementGuid>d08e51b8-cc67-4650-be72-45defa607660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsurancePlanDetails_InsurancePlanDetails_FirstName</value>
      <webElementGuid>9776c730-6c6c-4d4b-8f6a-ef9263c0f63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>765de2ee-bb44-44dd-85b0-bab44e8309f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsurancePlanDetails.InsurancePlanDetails.FirstName</value>
      <webElementGuid>797e3e40-84fd-4bc3-b9e5-71edfbcb007b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>b11ff4d0-36b6-4bfc-a40d-c8b389d48675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a40a4ffc-de4d-47fa-b2b8-04620b9f5cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QA</value>
      <webElementGuid>d684562f-2fe7-4cfc-9f81-4951055a76ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>9eb6682a-af7b-41bc-9267-e15201fad7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>InsurancePlanDetails_InsurancePlanDetails_FirstName-error</value>
      <webElementGuid>aa3c6c74-0c28-4567-bf60-18ccd3986fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fbcbb75-8237-4a31-881f-bb34c4ac4bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-20b7dd92992ed6785375939680675863</value>
      <webElementGuid>a0458e79-a4db-4b4f-8a56-cda1ab9b32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_FirstName']</value>
      <webElementGuid>7e8fac7c-ffe8-46d9-bcab-e64e2ebee9e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_FirstName']</value>
      <webElementGuid>b5e36ad5-2aed-4476-85d8-0befc1ab5aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsurancePlanDetails_InsurancePlanDetails_FirstName' and @name = 'InsurancePlanDetails.InsurancePlanDetails.FirstName' and @placeholder = 'First Name' and @type = 'text']</value>
      <webElementGuid>cdfc00e5-0d65-4576-a917-d4ea98a793a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
