<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_InsuredDOB</name>
   <tag></tag>
   <elementGuidId>d9ed1bee-bef6-431f-bb89-a544e73d91cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'InsuredDOB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InsuredDOB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#InsuredDOB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c10783a7-f1ea-4457-9032-54562ee23fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/04/1995</value>
      <webElementGuid>e32d9491-d8fe-43b1-8097-e0af14a06733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker valid</value>
      <webElementGuid>25d553f8-c7c2-4b76-bb50-01624ae6e849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>DOB</value>
      <webElementGuid>274e2745-6cda-4192-81c3-1d0603e01582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInsurance.PlanDetailsListItem</value>
      <webElementGuid>03ba8e86-5a45-43b3-8f28-a4d8433239a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>rgb(224, 244, 153)</value>
      <webElementGuid>7946eb52-edbd-438b-bdac-0c8945c69739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>DATE</value>
      <webElementGuid>539a1db6-7137-4aec-9021-05186ce24a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Insurance</value>
      <webElementGuid>26f1973d-d661-4093-b912-fde4b9dcfab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1afc7bbd-cb88-43e4-b11b-76505eae874f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>01/04/1995</value>
      <webElementGuid>6c97e328-4b69-43c7-96fd-5b9828a35851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e8eaf94-36b6-49df-8c40-7edd7d9cfc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field DOB must be a date.</value>
      <webElementGuid>44d7d96b-1162-454a-a065-fb338aecca1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsuredDOB</value>
      <webElementGuid>a901637a-fff3-4ad0-938d-23ba8872a048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsurancePlanDetails.InsurancePlanDetails.DOB</value>
      <webElementGuid>789e0e48-364f-4414-a549-c1324ba4ff38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cee5617-f28a-42e5-b49b-33924f3106c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>04ded7a3-180b-414c-b71e-ee91aa16d02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f49b6c74-eec5-4af9-ae62-f5146019f7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>InsuredDOB-error</value>
      <webElementGuid>0fdfdc4d-a1e4-442d-b181-3a064a2647d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e31d8e2f-4022-4b4e-bd23-dc378a1fdb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-257c999a744a0de40ec9465afe143b9b</value>
      <webElementGuid>5d2cb0e0-e1a4-4aae-a17f-f95ad9c633c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'InsuredDOB']</value>
      <webElementGuid>b52fbe1d-1c86-4444-96d0-f545513fe38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'InsuredDOB']</value>
      <webElementGuid>7867a824-a321-45f2-ab7c-3f4e886082c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsuredDOB' and @name = 'InsurancePlanDetails.InsurancePlanDetails.DOB' and @type = 'text']</value>
      <webElementGuid>521e5c0d-f8f1-4688-aae0-0da2bd4df653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
