<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All</name>
   <tag></tag>
   <elementGuidId>0d9aa646-bc6c-425b-b98e-4a507e609173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'changeGridAjax(true)']//*[@name = 'Type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;changeGridAjax\(true\)&quot;] [name=&quot;Type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51b2e4bf-c686-49cb-83bb-296e68a12493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ebf50755-5e7c-4b78-81a5-503368aeaf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>aa95051c-1603-4ebc-81f8-ae8dbce57951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7a0be0eb-9ad4-4c2a-b3c8-6175a4b1d589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-radio valid</value>
      <webElementGuid>1b1bcd72-2abe-423a-8bf6-5c001398b0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c0347e30794c5b1004b37e1297efa3ee</value>
      <webElementGuid>3ab32416-66c3-46ab-8947-6893f54916d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'changeGridAjax(true)']//*[@name = 'Type']</value>
      <webElementGuid>198d69cf-743b-4d59-a5ad-4c7b4df21488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'changeGridAjax(true)']//*[@name = 'Type']</value>
      <webElementGuid>8c7af912-a985-41d5-bae4-d93b3aa64e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Type' and @type = 'radio']</value>
      <webElementGuid>f5930a59-5ff9-4de0-bfa1-07a96b08cd35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
