<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_InsurancePlanInsuredID</name>
   <tag></tag>
   <elementGuidId>8cb79891-2a78-4422-b69b-aef0e07e88cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'InsurancePlanInsuredID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InsurancePlanInsuredID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#InsurancePlanInsuredID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c5106e6-9a50-4dd5-b6fb-24c9ab85ef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>InsuredID</value>
      <webElementGuid>33b8a1fd-b09a-4d56-8272-2a55e9b99012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInsurance.PlanDetailsListItem</value>
      <webElementGuid>b183d0da-9327-4764-b349-da0ee3d10d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>rgb(224, 244, 153)</value>
      <webElementGuid>70ab6a94-e21a-440c-99c2-64ae930bef0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Insurance</value>
      <webElementGuid>74ce0b8f-4e9e-427d-8049-3f89fd1c059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c878466e-2f55-4f36-9c0d-0cc6355c91b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>12345678</value>
      <webElementGuid>e4c26b5d-3bea-488a-a8d0-d4cf6cf4f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsurancePlanInsuredID</value>
      <webElementGuid>d9fdcf1f-b6dd-45f4-8c55-9c5a316a068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>804d3c78-b8df-4ab2-9178-bbe516d553bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1985082a-9417-4ca2-9073-9a270241526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsurancePlanDetails.InsurancePlanDetails.InsuredID</value>
      <webElementGuid>e6914104-2b56-47f4-8c76-dddd6ad8521c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f92d911-bdfe-4346-b66a-068c7d6aee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12345678</value>
      <webElementGuid>1552fd7b-835f-4de4-9fdf-4eb1cb8f5842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>b5f3737d-dc39-44cb-99a4-bb9e193e1a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-164b468f9fb35ab64eab7bac130e0c73</value>
      <webElementGuid>c3f668bd-d31a-4435-acc6-438cfefc9d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanInsuredID']</value>
      <webElementGuid>7602cc8b-20a5-483d-bfbb-90c9b3e965a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanInsuredID']</value>
      <webElementGuid>5b37ea7b-5940-4757-9a02-e9791f8f9ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsurancePlanInsuredID' and @name = 'InsurancePlanDetails.InsurancePlanDetails.InsuredID' and @type = 'text']</value>
      <webElementGuid>3d0b9c7e-d4fd-4dcb-a1c1-b4c96ef778c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
