<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GenderMale</name>
   <tag></tag>
   <elementGuidId>0e2387d3-a4b3-4262-aa09-42941fe54d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'GenderMale']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GenderMale</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;M&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c1f4e4f-2497-438d-bad5-ca9df1319fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>GenderMaleFemale</value>
      <webElementGuid>6a9de493-1649-444b-930f-fb6e70112cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInsurance.PlanDetailsListItem</value>
      <webElementGuid>2e1fd8a9-c8e7-4c58-ad67-2cff68ee9209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Insurance</value>
      <webElementGuid>b708e75e-2b0e-41ca-adb5-378d77e8f427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df756b5a-6076-4a75-a4d6-eb25adc3dd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-radiocheck-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e5ae7cd6-49e4-4bd6-a822-cd1101efd31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>37687fad-545c-4ac7-b235-e1323ec3d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GenderMale</value>
      <webElementGuid>2c3a0ed5-a7df-4d25-8f3f-7f46f4efc893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsurancePlanDetails.InsurancePlanDetails.GenderMaleFemale</value>
      <webElementGuid>7920c325-aa08-4449-a4b3-79f273c049ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6a382fd1-3816-49c3-9e6b-bd2680d75f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>f6ba48b8-f7b0-4036-a7ed-92551c4835b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-radio valid</value>
      <webElementGuid>23a6408c-051f-4dcb-85ce-5e7988d88bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>eb74225c-f970-407e-ba99-ff54e032c2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>253b55c6-6fc5-4083-833c-2558e4eff52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f472f6cb912f2d89f94554375faea25f</value>
      <webElementGuid>bb08fdbb-fed4-47a4-a7a1-9e69284372cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'GenderMale']</value>
      <webElementGuid>7b81aec7-7ddf-4ef1-9e97-eab5f7ecfa12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'GenderMale']</value>
      <webElementGuid>8b782d36-c69e-454c-b874-a3c739f9a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GenderMale' and @name = 'InsurancePlanDetails.InsurancePlanDetails.GenderMaleFemale' and @type = 'radio']</value>
      <webElementGuid>e2f117c0-380d-440c-acbe-9ecb8c842f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
