<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>d9df4cab-8e8e-42b5-a4d9-aeed2f711205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_LastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InsurancePlanDetails_InsurancePlanDetails_LastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a32929ba-a365-49ac-864d-5eda7e925a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input valid</value>
      <webElementGuid>72e55a58-cef8-4a38-ba41-6e0597f7a4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>2e35fe70-da3e-4185-96eb-ad2b6fe897a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~PatientInsurance.PlanDetailsListItem</value>
      <webElementGuid>76c910ba-eb6a-43ed-9202-9119fd646d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>rgb(224, 244, 153)</value>
      <webElementGuid>72993886-19d0-4796-9c7a-79a09fb924eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Insurance</value>
      <webElementGuid>1c0fafeb-59f9-4c48-9949-5eb4fad36115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e644d793-d0f0-4437-b363-10a4f577550b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>e91065d5-9cfc-429a-98c4-90391b777dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsurancePlanDetails_InsurancePlanDetails_LastName</value>
      <webElementGuid>cbbbc924-d050-405b-8609-304198dd5e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>095f2770-ecc1-44f6-a565-c0b91d1b29ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsurancePlanDetails.InsurancePlanDetails.LastName</value>
      <webElementGuid>129cc929-f2c7-471f-b52e-b540946d7ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>64ed79b4-0c50-4ce3-8e0b-49b63cc537fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d0de22b-cc65-4c46-b85a-e9db6ea7c692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>05a10acf-784c-474a-8117-d817d9940269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>a4c9bb8e-a474-4b5b-a66b-5f5bad70c688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>InsurancePlanDetails_InsurancePlanDetails_LastName-error</value>
      <webElementGuid>88d61fa5-b31e-4243-938f-f12b53283382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b2639102-38a2-4a55-839e-6e419c2abb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4cc2e6e076e54d5c59824dbb5ca6aa5e</value>
      <webElementGuid>198d3cde-92cd-4c5f-ab6c-caed32d4c4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_LastName']</value>
      <webElementGuid>464a4b50-588b-468c-ae02-f3b32e8c27f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'InsurancePlanDetails_InsurancePlanDetails_LastName']</value>
      <webElementGuid>a7a3b136-520b-42b6-ba0f-80d59cbecc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsurancePlanDetails_InsurancePlanDetails_LastName' and @name = 'InsurancePlanDetails.InsurancePlanDetails.LastName' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>b8b924d8-a5fa-4b7a-b550-3422072586ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
