<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>1fd68c07-23c9-4a6c-b3bd-032f4dd8109f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;changeGridAjax\(true\)&quot;] .icons span:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@onclick='changeGridAjax(true)']//input[@name='Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Insurance label >> internal:has-text=&quot;All&quot;i >> span >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc336d52-8599-4cac-ac7d-35a5e8f4375e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-checked</value>
      <webElementGuid>d3ec25d5-f050-4a82-9a04-c182e2d28b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7cf34c2b98b87d3bc03021dfcec1f1ea</value>
      <webElementGuid>9631596b-eff0-4514-bebe-f2c76566b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'changeGridAjax(true)']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' icons ')]//*[(name() = 'span') and (position() = 2)]</value>
      <webElementGuid>54232b58-ff14-4ec8-bd26-e7d82940d053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@onclick='changeGridAjax(true)']//input[@name='Type']</value>
      <webElementGuid>be4f2ea6-1086-4e5f-9ebd-f17c42bc636a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
