<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chat Bot Enter Text Area</name>
   <tag></tag>
   <elementGuidId>53ec8ced-03dd-45fa-a9e8-647a18b154ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.evaa-input-textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>df632e32-41f6-4979-b184-7b1f974a0971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ede8fc2c-b589-42f3-875e-491782a5ce21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>evaa-input-textarea</value>
      <webElementGuid>2e84b454-0ecd-4db9-9da5-483ad3c525d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;evaa-chat relative flex h-full flex-col overflow-hidden&quot;]/div[@class=&quot;relative flex min-h-0 flex-1 flex-col overflow-hidden&quot;]/div[@class=&quot;evaa-chat-bottom&quot;]/div[@class=&quot;evaa-input-wrapper&quot;]/div[@class=&quot;evaa-input-box&quot;]/textarea[@class=&quot;evaa-input-textarea&quot;]</value>
      <webElementGuid>e5ac1491-2b5f-4c51-907f-c16aa4bd56db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Appointment Booking/Chat Bot Appt Book/iframe_LinkedIn_evaas-iframeId (1)</value>
      <webElementGuid>c8da81b9-af76-4914-ae11-aa5ca5714dc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/textarea</value>
      <webElementGuid>bddf3e7e-d9b1-4864-85a7-cf2a36e12c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fad36638-5db8-46dc-a6bf-5d129ffbf6a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
