<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , evaas-iframeId, , ))_evaas-iframeId</name>
   <tag></tag>
   <elementGuidId>c7da7199-7a39-41a6-9e71-a88786ffe6fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='evaas-iframeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#evaas-iframeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#evaas-iframeId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>13fdfee2-4c9c-4adf-8f4c-1a5addb56d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evaas-iframeId</value>
      <webElementGuid>c5ef03ed-e859-4790-b914-5ac1edc97a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>bbad03a3-9902-4485-bae6-b4e973e6dc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true</value>
      <webElementGuid>519362f6-b9d4-411c-8112-a395561ad8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-visible</value>
      <webElementGuid>50092cef-c774-4839-a1c6-5798bdd0c764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;evaas-iframeId&quot;)</value>
      <webElementGuid>95b38c28-7f39-4d04-8cb6-ba483a9fd11d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='evaas-iframeId']</value>
      <webElementGuid>206c5b86-ddb2-498c-8a6b-67c999d4b26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>53586e94-cf29-478c-bde6-44aeff6166d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'evaas-iframeId' and @src = 'https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true']</value>
      <webElementGuid>b98b785f-d200-45e8-9063-ec38eb9e58ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
