<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>37497498-260d-410a-ac39-9a0c5b9ac20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div[2]/div[2]/button/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Settings Settings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>46dac713-6562-4656-a2c7-cd71cf7a54b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml,%3csvg%20width='16'%20height='16'%20viewBox='0%200%2016%2016'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M4%206L8%2010L12%206'%20stroke='%23300D21'%20stroke-width='1.33333'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3c/svg%3e</value>
      <webElementGuid>c029eaeb-edaf-4073-bcc5-7f5c4eb86873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>7bb28e40-918a-4b0f-9d37-e0c2148ff6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-vh-100 d-flex flex-column&quot;]/header[@class=&quot;navbar navbar-expand-lg bg-white shadow-sm&quot;]/div[@class=&quot;container-fluid px-4&quot;]/div[@class=&quot;d-flex align-items-center gap-2&quot;]/div[@class=&quot;dropdown&quot;]/button[@class=&quot;btn px-2 d-flex gap-1 bg-transparent border-0 nav-icon-btn show&quot;]/img[2]</value>
      <webElementGuid>4706c3da-b551-4229-b047-ce9fac3b7bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/div[2]/button/img[2]</value>
      <webElementGuid>c301dacd-ea32-4b1f-b99b-bdfb05d604db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Settings'])[2]</value>
      <webElementGuid>36a97a97-8517-4240-ba4b-6011387424aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img[2]</value>
      <webElementGuid>2dbd26fc-d524-41e3-a9f5-cc94f39c2b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = concat(&quot;data:image/svg+xml,%3csvg%20width=&quot; , &quot;'&quot; , &quot;16&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;16&quot; , &quot;'&quot; , &quot;%20viewBox=&quot; , &quot;'&quot; , &quot;0%200%2016%2016&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;none&quot; , &quot;'&quot; , &quot;%20xmlns=&quot; , &quot;'&quot; , &quot;http://www.w3.org/2000/svg&quot; , &quot;'&quot; , &quot;%3e%3cpath%20d=&quot; , &quot;'&quot; , &quot;M4%206L8%2010L12%206&quot; , &quot;'&quot; , &quot;%20stroke=&quot; , &quot;'&quot; , &quot;%23300D21&quot; , &quot;'&quot; , &quot;%20stroke-width=&quot; , &quot;'&quot; , &quot;1.33333&quot; , &quot;'&quot; , &quot;%20stroke-linecap=&quot; , &quot;'&quot; , &quot;round&quot; , &quot;'&quot; , &quot;%20stroke-linejoin=&quot; , &quot;'&quot; , &quot;round&quot; , &quot;'&quot; , &quot;/%3e%3c/svg%3e&quot;) and @alt = 'Settings']</value>
      <webElementGuid>3309c2f3-7b5b-44c0-947d-f82af2be4182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
