<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_closed-Sunday</name>
   <tag></tag>
   <elementGuidId>b5b12e3b-83bb-4e51-aa8d-3b23d952417c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closed-Sunday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='closed-Sunday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closed-Sunday</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb0fda7e-c19d-472b-8456-869192fbd02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input</value>
      <webElementGuid>99b09910-e5a3-416b-89d6-22739a7c7355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>28dfb13e-2244-4081-9b41-979c21003b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closed-Sunday</value>
      <webElementGuid>518e9b2f-95c1-463b-bff0-d090280d53d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closed-Sunday&quot;)</value>
      <webElementGuid>823647dc-7529-46be-9ca1-8dee28f876f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='closed-Sunday']</value>
      <webElementGuid>8cc3d2b6-1958-45bc-9cfa-ee1c9f81e9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[4]/div/div/div[2]/div/div/div[16]/div/div[4]/div/div[2]/div[3]/input</value>
      <webElementGuid>f794a168-816f-43e2-af3c-a9bb0e49ac34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[3]/input</value>
      <webElementGuid>2038c165-94ef-4091-9a39-6e20fc090278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'closed-Sunday']</value>
      <webElementGuid>6be3ff4f-4068-417b-875b-75200060e0aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
