<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EliteCare Clinic_org-revolution</name>
   <tag></tag>
   <elementGuidId>26358c83-0c5b-47b3-98d2-5fecd240ac81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-revolution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='org-revolution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Revolution&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>880e4d7a-5bd8-4e8b-ba6d-333ee2a61eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ml-0</value>
      <webElementGuid>af7a64f2-eabd-47c5-b2ac-f6c1c2b3481b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cfe7e543-406a-4863-87de-bcf799f305a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-revolution</value>
      <webElementGuid>482d2581-4ba8-4367-a8b0-0dc192643b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-revolution&quot;)</value>
      <webElementGuid>1b6d6d10-ab37-40c3-9f35-12f71edda415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='org-revolution']</value>
      <webElementGuid>2597d763-8b6b-4bf7-bec7-831d7e0a1803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='practice-locations-section']/div[2]/div[35]/div/input</value>
      <webElementGuid>92798fe7-aa3b-4bec-93c3-2c3977080ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/div/input</value>
      <webElementGuid>bf4846ff-aa93-4497-ba32-5c564c8d242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'org-revolution']</value>
      <webElementGuid>6df869e0-679c-4bb4-a2bc-c77af174e9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
