<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_closed-Saturday</name>
   <tag></tag>
   <elementGuidId>58e13574-2c1e-48ac-81db-3d699210ba5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closed-Saturday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='closed-Saturday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closed-Saturday</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15ef2519-f4ba-4ddc-a736-526557669aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input</value>
      <webElementGuid>11f35e3b-45d1-40c8-87b0-fb49dcfea197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eb3ecc5f-6be9-4888-b32c-6c79787097d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closed-Saturday</value>
      <webElementGuid>f2c017ef-f09d-475b-9ac7-da9bbaeca850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closed-Saturday&quot;)</value>
      <webElementGuid>adc26d97-f162-4e6f-af8a-80e727933de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='closed-Saturday']</value>
      <webElementGuid>b75a891a-37e9-4021-b815-6534c99c832e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[4]/div/div/div[2]/div/div/div[16]/div/div[3]/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>b9194ca0-1ed8-4e72-a5a4-1c155900cdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>466442e7-e645-4b69-8f7c-3a2170798ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'closed-Saturday']</value>
      <webElementGuid>ed1bde2a-6679-4dc9-b605-766efe566e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
