<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_evaas-iframeId</name>
   <tag></tag>
   <elementGuidId>d200fedd-73b8-4e4d-aea2-4218bf45dba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'evaas-iframeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#evaas-iframeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#evaas-iframeId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>06ebd99b-b5ec-45cb-a5ae-a57ae15fc2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evaas-iframeId</value>
      <webElementGuid>ef5c4e14-18fb-4ddc-9376-a09ef6e22689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>c2ee1938-f462-4faa-bb94-f321e8e9721b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true</value>
      <webElementGuid>31fc4a60-640b-482f-8379-9cd45e973aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-visible</value>
      <webElementGuid>0c974811-bbdc-4f2c-9c1d-bdf9a91fa7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5cc6c57ae394525d64f02ff90b040411</value>
      <webElementGuid>6c1fd42f-d91e-4bfa-a0a9-951090deda2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>b5d28643-233b-49ef-867c-1c20bd51bbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>7fa47e70-ceeb-4f21-a934-d446dead8dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'evaas-iframeId' and @src = 'https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true']</value>
      <webElementGuid>39278918-19d0-4bfa-836f-5ac76e1ddb75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
