<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload_1</name>
   <tag></tag>
   <elementGuidId>ac7f1cd6-faf0-47d7-8a11-7300504113d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-btn ') and (position() = 1)])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.wizard-upload-btn:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>164ce488-dbef-4ce0-9772-46fd31f61ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23ee5a3f-52ca-4f17-ac27-da486d969d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-upload-btn</value>
      <webElementGuid>c97bad50-d7c2-4d44-b6e2-672c7bee1973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>09f3812e-bfba-4615-907e-6d40eb8c2e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4fec00a615602f6238d9cd588e658d5e</value>
      <webElementGuid>75bf7a3e-c64b-46e5-a731-164e53c43258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-btn ') and (position() = 1)]</value>
      <webElementGuid>2f91153e-1475-4ad8-b0e0-59a1d17e8008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Book Appt With Ins/EVAA.AI React/iframe_evaas-iframeId</value>
      <webElementGuid>5835ab2d-bc20-4b8b-a873-322e50f37f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-btn ') and (position() = 1)]</value>
      <webElementGuid>d86ea898-f391-4ec8-a44a-195f570080b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//button[@type = 'button' and (text() = 'Upload' or . = 'Upload')])[2]</value>
      <webElementGuid>7b1017f0-0fa1-4fa9-8878-471f2cc9a40c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
