<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_evaas-iframeId</name>
   <tag></tag>
   <elementGuidId>51de1fa6-8377-46c4-b418-d4cd1f65ec25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#evaas-iframeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'evaas-iframeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#evaas-iframeId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a73e1f2f-cacc-4258-9b1c-48eca8ed762d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evaas-iframeId</value>
      <webElementGuid>a950cb76-1074-4fb7-b3a1-d4fe342bf5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>9fa6e28d-1c4e-4190-b2e2-37fccd890eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true</value>
      <webElementGuid>9130948b-e084-4f46-aaab-0b2a4bd0c34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-visible</value>
      <webElementGuid>a36a5ede-8efa-4923-bdd3-6a771fc1e4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5cc6c57ae394525d64f02ff90b040411</value>
      <webElementGuid>12217bfd-be57-4f1d-a4f1-74985bf00e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>d3fe9e6f-e647-4435-8ffa-0a2cd8e978d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'evaas-iframeId']</value>
      <webElementGuid>ed317681-51c4-4dbb-aca7-f2a663b805d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'evaas-iframeId' and @src = 'https://assistant-qa.evaa.ai/qa5/Q8lr1O?host=qa5.eyeclinic.ai&amp;embed=true']</value>
      <webElementGuid>c374ba62-c2cd-4a79-9abe-8ebbf7c43001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
