<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hidden_1</name>
   <tag></tag>
   <elementGuidId>db4624d5-28e8-4825-b151-e716d2357f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.wizard-upload-box:nth-child(2) [type=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-box ') and (position() = 2)]//*[@type = 'file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Back SideUpload or take a photo of the back of your insurance cardUploadCamera$/ >> input[type=&quot;file&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95d21c17-4627-44a5-b0d0-abff10170fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*,application/pdf</value>
      <webElementGuid>f48d8837-76d6-4574-b08f-c155063c4f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden</value>
      <webElementGuid>b32c877c-697e-4e82-91e0-6ffc0e82179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ac1862ae-ac3a-4650-8c83-54a309a4b017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1ff42abf331d2dc0191eddbfa5662f76</value>
      <webElementGuid>98cc66cc-e310-4001-b831-7602319a816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-box ') and (position() = 2)]//*[@type = 'file']</value>
      <webElementGuid>290982ba-b81c-44c9-b1c8-a00fa1ff8eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Book Appt With Ins/EVAA.AI React/iframe_evaas-iframeId</value>
      <webElementGuid>cda57ab2-23a9-47b8-983f-5eef65979eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wizard-upload-box ') and (position() = 2)]//*[@type = 'file']</value>
      <webElementGuid>bea88a39-1834-4b62-a34a-20ff78b49fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>32cd4dc8-3aca-444b-a4a1-cf83a56e2c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
