<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name</name>
   <tag></tag>
   <elementGuidId>cea5f2e2-9770-4d29-baef-d52e3ebf621c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuranceFN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'insuranceFN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>165c3065-3179-4db7-a834-81e586c15860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuranceFN</value>
      <webElementGuid>5dcff0b2-64bb-4f40-838f-aec35d1c9a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-input</value>
      <webElementGuid>cb0916c2-c6d7-49a3-9b03-8342d5b9156a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>f0d05d62-f6d3-40a7-8852-ff2ce32a1db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QA</value>
      <webElementGuid>bf19be4e-fd16-41a4-bebc-bfd2a4b9a459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-93c1394b99f209f581bfacd4cb223a6d</value>
      <webElementGuid>2e59f03b-8ff1-464f-a1b6-04d41d9d9029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'insuranceFN']</value>
      <webElementGuid>4322bb7c-e091-43c4-8daa-582400cb3b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Book Appt With Ins/EVAA.AI React/iframe_evaas-iframeId</value>
      <webElementGuid>8b5d2583-0dbc-4233-a090-2a7e70305634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'insuranceFN']</value>
      <webElementGuid>08817449-33df-4148-b3a3-0b83dda7ab1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insuranceFN' and @placeholder = 'First Name']</value>
      <webElementGuid>fe3723f5-823a-49d1-a175-ec5909f84255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
