<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>1abffa04-12fa-4c15-b0cd-b55ee5752ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuranceLN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'insuranceLN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c85b433-15b3-4aa5-9f13-3d223f50a4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuranceLN</value>
      <webElementGuid>a4deca1e-9828-4c72-8ed3-bd741e684201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-input</value>
      <webElementGuid>6621ab50-d29c-45f2-ab5d-c4a21f24515e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>10af3ebd-15c2-42aa-a80d-6d05e9291667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>b2dfa65d-f38f-4b2e-b042-8d72cd35731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f5a63a6f31070084b0d52df72f53ae74</value>
      <webElementGuid>6657c4fa-ba41-44ad-a674-78b278314e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'insuranceLN']</value>
      <webElementGuid>fc3855b3-8977-4d44-a9d8-9cdb78816c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Book Appt With Ins/EVAA.AI React/iframe_evaas-iframeId</value>
      <webElementGuid>9818431c-e7dd-4fc5-95c0-84a704f892af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'insuranceLN']</value>
      <webElementGuid>d2271f9f-3f54-4684-a54e-21b8e837f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insuranceLN' and @placeholder = 'Last Name']</value>
      <webElementGuid>952cefc2-cbb5-4e0d-9f0b-4f554ab1995a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
