<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Gender</name>
   <tag></tag>
   <elementGuidId>aa916cb9-f429-43ee-9c15-1fb12eaac137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genderSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'genderSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gender*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98886e70-68dc-4a56-b7f2-978a6d4d17a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genderSelect</value>
      <webElementGuid>142701ee-6c57-4156-92a4-89b704193061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wizard-select</value>
      <webElementGuid>3151b11f-0725-4100-942f-3640e5ae4266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectMaleFemaleOther</value>
      <webElementGuid>99431415-be0f-4a5f-bb16-2126a4c69e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c24581321953d2e9743fa05b18644b10</value>
      <webElementGuid>ac51d83e-8dd3-4d84-aebf-5950439dff4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'genderSelect']</value>
      <webElementGuid>8844dbaa-236f-4812-8e40-d17a51f8ead0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Book Appt With Ins/EVAA.AI React/iframe_evaas-iframeId</value>
      <webElementGuid>99151341-d82a-4ba6-b237-6fcaaf8bcfea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'genderSelect']</value>
      <webElementGuid>4103a518-53d2-4a45-8d1b-65825c9d3c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'genderSelect' and (text() = 'SelectMaleFemaleOther' or . = 'SelectMaleFemaleOther')]</value>
      <webElementGuid>da6fc5f5-c9db-40ad-a164-71d9e34aa772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
