<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnEmailVerify</name>
   <tag></tag>
   <elementGuidId>7e055a66-35c1-4861-82aa-dac168cdb8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnEmailVerify']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnEmailVerify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Verify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e02df07e-d1bb-4867-94a9-3145fb1f6a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca9e3be6-566b-449f-bad4-0c11ceb40f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>f4bfe80e-95ed-4c7e-9e2d-dc0b8915c3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button small primary marL40 font18</value>
      <webElementGuid>a32fcfa8-4ae6-4f12-86a4-f60bdfef7515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEmailVerify</value>
      <webElementGuid>e82a4817-191d-49e0-bf08-b05659a23be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: VerifyOTP('Email')</value>
      <webElementGuid>b3cf1db4-4b4c-41ad-b0e9-07b76fe1d3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3c72dc6a286d902f72178f4e0e8be518</value>
      <webElementGuid>56b309e3-ec29-4fc3-af15-4b961a96ebab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnEmailVerify']</value>
      <webElementGuid>2600f861-aaf7-4869-b6c0-fde238ce13db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnEmailVerify']</value>
      <webElementGuid>4f9a0101-efd7-4a12-bf16-3e7face06bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnEmailVerify']</value>
      <webElementGuid>6759fc8b-9cdc-4878-97f6-ec1f984d5c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
